MuckRock/documentcloud-frontend

- src/pages/viewer/Sidebar.svelte
Without a source: https://deploy-preview-79--documentcloud-frontend.netlify.app/documents/20512972-hb0020
With a source: https://deploy-preview-79--documentcloud-frontend.netlify.app/documents/20512828-board-of-elections-2021-03-12-board-agenda
> Add the Source to document sidebar

- package-lock.json
- package.json
- src/langs/json/en.json
- src/pages/app/Documents.svelte
- src/pages/viewer/ThumbnailBody.svelte
- src/pages/viewer/pane/ModifyPane.svelte
- webpack.app.config.js
- webpack.base.config.js
- webpack.embed.config.js
Rotate button now reads as "Rotate" in English whereas it was "Move" before, often resulting in multiple "Move" buttons when there were multiple pages in view.
> Rotate page i18n

- package-lock.json
- package.json
This was previously tested on staging. Now it has been caught up to master.
> update axios and remove hugo. Rebase master onto this branch.

- src/langs/json/en.json
Updating access setting string to be more accurate in light of the noindex option.
> Updating access setting string

- package-lock.json
- package.json
- src/common/Dropdown.svelte
- src/langs/json/en.json
- src/pages/app/ActionBar.svelte
- src/pages/app/menus/AddonsMenu.svelte
- Bigger, darker text for add-ons help link
- Add a New! badge
> Shout about Add-ons a bit

- package-lock.json
- package.json
- src/common/Dropdown.svelte
- src/langs/json/en.json
- src/pages/app/ActionBar.svelte
- src/pages/app/menus/AddonsMenu.svelte
- Bigger, darker text for add-ons help link
- Add a New! badge
> Production push: Shout about Add-ons a bit

- src/common/Modal.svelte
- src/common/UploadOptions.svelte
- src/langs/json/en.json
- src/pages/app/Documents.svelte
- src/pages/app/EmbedFooter.svelte
- src/pages/app/Paginator.svelte
- src/pages/app/UploadDialog.svelte
- src/pages/home/HomeTemplate.svelte
- src/pages/viewer/Sidebar.svelte
- Fix duplicated redaction text
- Highlight that Textract is a premium feature and you should pay for it
> Highlight OCR options

- src/common/Modal.svelte
- src/common/Select.svelte
- src/common/UploadOptions.svelte
- src/langs/json/en.json
- src/pages/app/Documents.svelte
- src/pages/app/EmbedFooter.svelte
- src/pages/app/Paginator.svelte
- src/pages/app/UploadDialog.svelte
- src/pages/home/HomeTemplate.svelte
- src/pages/viewer/Sidebar.svelte
> Show OCR options to non-premium users

- src/common/Dropdown.svelte
- src/pages/app/ActionBar.svelte
- src/pages/app/App.svelte
- src/pages/app/AuthSection.svelte
- src/pages/app/menus/AddonsMenu.svelte
- src/pages/app/sidebar/OrgUsers.svelte
- src/pages/viewer/Viewer.svelte
Events we're tracking:
- Any time someone opens a dropdown
- Clicks on links in the `Projects` and `Add-Ons` menus
- Toggling the "Users in organization" widget in the sidebar
View events here: https://plausible.io/documentcloud.org
> Event tracking

- src/pages/viewer/Sidebar.svelte
- src/pages/viewer/controls/Hamburger.svelte
- src/pages/viewer/controls/ViewDropdown.svelte
- src/pages/viewer/controls/Zoom.svelte
All the things you can click that don't make API calls.
- hamburger
- zoom
- sharing
Also made a few button-like things actual buttons for A11y.
> Viewer events

- src/common/Dropdown.svelte
- src/pages/app/ActionBar.svelte
- src/pages/app/App.svelte
- src/pages/app/AuthSection.svelte
- src/pages/app/menus/AddonsMenu.svelte
- src/pages/app/sidebar/OrgUsers.svelte
- src/pages/viewer/Sidebar.svelte
- src/pages/viewer/Viewer.svelte
- src/pages/viewer/controls/Hamburger.svelte
- src/pages/viewer/controls/ViewDropdown.svelte
- src/pages/viewer/controls/Zoom.svelte
- Add plausible to App and Viewer for logged-in users
- Don't init orgs and users for embeds
- Add events to app view
- Viewer events
See all the events we're tracking here: https://plausible.io/documentcloud.org/settings/goals
> Production push: Plausible on DocCloud

- src/common/dialog/AddonDispatchTsDialog.svelte
- src/langs/json/en.json
Handle anonymous users linking to add-ons:
> Sign in to use add-ons

- src/manager/layout.js
- src/router/router.js
Remove add-on specific query args when the modal closes.
> URL cleanup

- src/manager/addons.js
Fixes a bug @duckduckgrayduck found dispatching add-ons.
> Compute add-on indexes using both browser and active add-ons

- src/manager/addons.js
> Production push: Compute add-on indexes using both browser and active add-ons

- src/common/dialog/AddonDispatchTsDialog.svelte
- src/manager/layout.js
Fixes this: https://www.notion.so/muckrock/Klaxon-UI-blanks-out-text-inputs-eade6fc185c84a1a97314fc625c04754
> Production: Only set activeEvent in loadEvent

- src/api/addon.js
- src/common/dialog/AddonBrowserDialog.svelte
- src/manager/addons.js
See it on staging: https://www.staging.documentcloud.org/app?q=%2Buser%3Afreeuser-100013#add-ons
> Fix API calls for add-on pagination

- src/manager/orgsAndUsers.js
- src/pages/app/sidebar/OrgUsers.svelte
This has a corresponding backend PR
> show admin info on sidebar

- src/langs/json/en.json
- src/pages/app/Anonymous.svelte
- src/pages/app/Documents.svelte
Adds some explanatory text to anonymous users who come to the search page
> Add anonymous copy

- src/addons/dispatch/Dispatch.svelte
- src/addons/dispatch/Header.svelte
- src/common/Toast.svelte
- src/common/stories/Toast.stories.ts
- src/langs/json/en.json
- src/manager/toast.js
This uses the existing Toast UI component to display messages to the user confirming successful add-on runs/schedules, or providing error messages.
- Adds stories for Toast component
- Additional styling and props for Toasts
> Present toasts with user feedback when dispatching addons

- src/addons/Drawer.svelte
- src/addons/browser/AddOnList.svelte
- src/addons/browser/AddOnListItem.svelte
- src/addons/browser/Browser.svelte
- src/addons/browser/Filters.svelte
- src/addons/browser/SearchInput.svelte
- src/addons/dispatch/Form.svelte
- src/style/variables.css
A collection of small fixes based on testing:
- Increases add-on browser page size
- Uses radio selection for sidebar navigation. This gives the feeling that you're browsing individual sections, not applying filters to a list.
- Style fixes
> Add-on Fixes

- src/addons/dispatch/Dispatch.svelte
- src/addons/dispatch/ScheduledInset.svelte
- src/addons/dispatch/stories/ScheduledInset.stories.svelte
- src/addons/fixtures/klaxon-scheduled.json
- src/addons/runs/Scheduled.svelte
- src/addons/runs/ScheduledEvent.svelte
Have this in the old UI. Now we have it in the new one.
> See scheduled runs from Dispatch

- src/addons/browser/Filter.svelte
- src/addons/browser/Filters.svelte
- src/addons/dispatch/Header.svelte
- src/addons/dispatch/stories/Header.stories.svelte
- src/addons/runs/ScheduledEvent.svelte
- src/common/Button.svelte
- src/common/Toast.svelte
- src/manager/layout.js
- src/pages/app/menus/AddonsMenu.svelte
- Removes icon from categories
- Adds tips about what the featured and pinned sections are
- moving around menu items
> More UI bugfixes

- src/addons/progress/stories/AddonRun.stories.svelte
- src/addons/progress/stories/AddonStatus.stories.svelte
- src/addons/runs/HistoryEvent.svelte
- src/addons/runs/stories/HistoryEvent.stories.svelte
- Adds stories for HistoryEvent statuses
- Adds stories for add-on progress components
> Progress on progress

- src/addons/dispatch/Dispatch.svelte
- src/addons/dispatch/Header.svelte
- src/addons/progress/AddonRun.svelte
- src/addons/progress/AddonStatus.svelte
- src/ticker/ticker.js
- src/util/batchDelay.js
- src/util/batchDelay.test.js
- Resets dispatch form when returning back to browser
- Only schedule add-ons that aren't one-off
- poll locally
> Local polling

- src/addons/progress/AddonRun.svelte
- src/addons/progress/AddonStatus.svelte
- src/langs/json/en.json
Make sure all text in the Add-On progress components run through internationalization.
> Progress translations

- src/addons/dispatch/Form.svelte
- src/addons/dispatch/fields/Checkbox.svelte
- src/addons/dispatch/fields/Number.svelte
- src/addons/dispatch/fields/Text.svelte
> Default values for Text, Number and Checkbox fields

- src/addons/dispatch/Dispatch.svelte
All of this has happened before, and all of this will happen again.
> Load initial add-on values from querystring

- src/assets/checkline.svg
- src/assets/checkmark.svg
- src/common/Checkbox.svelte
> Center checkboxes and remove unused assets

- src/pages/app/sidebar/ProjectFilters.svelte
- src/pages/app/sidebar/Projects.svelte
- src/pages/app/sidebar/Sidebar.svelte
> Only show user-related sidebar things for logged-in users

- package-lock.json
- package.json
- src/api/auth.js
- src/langs/json/en.json
- src/pages/FlatPage.svelte
- src/pages/NotFound.svelte
- src/util/lazyComponent.js
- webpack.base.config.js
- Load flat page content from the new API endpoint and add titles
- fix content width
Production push.
> Flatpage titles

- .gitignore
- package-lock.json
- package.json
- public/mockServiceWorker.js
- src/main.js
- webpack.base.config.js
> Sentry setup

- src/pages/viewer/Sidebar.svelte
> Added entries for googlecv and ocrspace1 to sidebar

- src/pages/viewer/Sidebar.svelte
The others, for Google Cloud Vision and OCR Space work, see https://www.documentcloud.org/documents/23963211-acknowledgement-letter
This is just adding one more entry for Azure
> Add Azure Document Intelligence to OCR engine map for sidebar

- src/api/viewer.js
It works on staging, now to bring it to production
> Cache-bust on the viewer for jsonurl

- package-lock.json
- package.json
- preprocess.config.js
- src/api/orgAndUser.js
- src/api/session.js
- src/manager/manager.js
- src/viewer/document.js
- src/viewer/modification/modification.js
- webpack.app.config.js
- webpack.base.config.js
- webpack.config.js
- webpack.embed.config.js
This makes the frontend run explicitly in module mode. See the differences here: https://nodejs.org/docs/latest-v18.x/api/packages.html#determining-module-system
Users shouldn't see any change with this.
Closes #327
> Switch to ES Module format

- .gitignore
- src/pages/FlatPage.svelte
- src/pages/NotFound.svelte
> Include credentials on FlatPage api calls

- src/addons/dispatch/Header.svelte
Merge https://github.com/MuckRock/documentcloud/pull/188 first.
> Show instructions if present

- src/pages/app/fixtures/me.json
- src/pages/app/sidebar/Projects.svelte
- src/pages/app/sidebar/stories/Project.stories.svelte
- src/pages/app/sidebar/stories/ProjectFilters.stories.svelte
- src/pages/app/sidebar/stories/Projects.stories.svelte
- src/pages/app/sidebar/stories/Sidebar.stories.svelte
- src/pages/app/stories/mock.js
Have mocks, but it looks like something isn't connecting. Not going to debug this as much as I might, because there's lots here I'd like to rethink.
Closes #380
> Basic sidebar stories

- src/pages/viewer/pane/stories/ActionPane.stories.svelte
- src/pages/viewer/pane/stories/AnnotatePane.stories.svelte
- src/pages/viewer/pane/stories/ModifyPane.stories.svelte
- src/pages/viewer/pane/stories/RedactPane.stories.svelte
- src/pages/viewer/pane/stories/SearchPane.stories.svelte
- src/pages/viewer/pane/stories/SelectNotePane.stories.svelte
Need to think about how to make these stateless, since ultimately they're just banners.
> Basic action pane stories. Some won't work without state management.

- src/main.js
Adjusting our sample rate so we don't blow through Sentry limits.
> Try half sampling

- src/routes/app/+page.svelte
Does what it says on the tin.
This has a typescript error in it that's fixed in #460. Not going to touch it here because I don't want to create conflicts.
> Make paginator work with async search results

- src/lib/components/MainLayout.svelte
- src/lib/components/stories/MainLayout.stories.svelte
This adds two slots to the `MainLayout`: `modal` above and `basement` below. It also adds two props to `MainLayout`, `modal` to control modal visibility, and `basement` to control which side the basement should appear on.
> Adds Basement and Modal layers to MainLayout

- src/lib/components/MainLayout.svelte
- src/lib/components/common/SignedIn.svelte
- src/lib/components/stories/MainLayout.stories.svelte
- src/routes/app/+layout.svelte
- src/routes/app/sidebar/Documents.svelte
This provides a utility component, `SignedIn`, that renders its primary slot if the user is present in context. It takes an optional slot, named "signedOut", to display if no user is available. 
This also wraps some layout and page components with the new component, to control presentation for logged-out users.
> Adds SignedIn component

- src/lib/components/sidebar/SidebarItem.svelte
- src/lib/components/sidebar/stories/SidebarItem.stories.svelte
Also allows for customized colors
> Adds an active state to SidebarItem

- src/routes/(embed)/documents/[id]/annotations/[note_id]/+page.svelte
- src/routes/(embed)/projects/[project_id]/+page.svelte
- src/routes/(embed)/stories/project-embed.stories.svelte
- **Fix box-sizing on note embed**
- **Use columns, not flex, for project embed**
> sveltekit embed cleanup

- src/langs/json/en.json
- src/routes/documents/[id]-[slug]/sidebar/Actions.svelte
- src/routes/documents/[id]-[slug]/sidebar/DocumentMetadata.svelte
Polish some markup and a little `i18n`
> viewer cleanup

- src/lib/components/documents/PDF.svelte
- src/lib/components/documents/PDFPage.svelte
- src/lib/components/documents/Page.svelte
- src/lib/components/documents/ResultsList.svelte
- src/lib/components/documents/Text.svelte
- src/lib/components/documents/ThumbnailGrid.svelte
- src/routes/documents/[id]-[slug]/+layout.svelte
- src/routes/documents/[id]-[slug]/+page.svelte
- src/routes/documents/[id]-[slug]/+page.ts
Compare:
Optimized: https://deploy-preview-546.muckcloud.com/documents/20006211-22-506_k53l/
Not optimized: https://deploy-preview-542.muckcloud.com/documents/20006211-22-506_k53l/
> sveltekit viewer optimization

- src/common/icons/Grid.svelte
- src/langs/json/en.json
- src/lib/api/documents.ts
- src/lib/api/types.d.ts
- src/routes/documents/[id]-[slug]/+layout.svelte
- src/routes/documents/[id]-[slug]/+page.svelte
- src/routes/documents/[id]-[slug]/sidebar/Actions.svelte
- src/routes/documents/[id]-[slug]/sidebar/DocumentMetadata.svelte
Little cleanup things before we move onto bigger stuff.
> Rename thumbnails -> grid, plus some cleanup

- src/config/config.js
- src/lib/components/documents/Note.svelte
> Move ALLOWED_TAGS and ALLOWED_ATTRS to config

- package-lock.json
- src/lib/components/addons/tests/__snapshots__/AddOnListItem.test.ts.snap
- src/lib/components/addons/tests/__snapshots__/AddOnsNavigation.test.ts.snap
- src/lib/components/documents/PDF.svelte
- src/lib/components/documents/PDFPage.svelte
- src/lib/components/documents/Text.svelte
- src/lib/components/documents/TextPage.svelte
- src/lib/components/documents/stories/PDFPage.stories.svelte
- src/lib/components/documents/stories/TextPage.stories.svelte
- src/lib/utils/search.ts
- src/lib/utils/tests/search.test.ts
- src/routes/documents/[id]-[slug]/+page.svelte
- src/routes/documents/[id]-[slug]/+page.ts
This is all in-browser, using a regular expression to match text. Trying to be as simple as possible, but no simpler.
Dependencies are also updated.
> Very basic in-document search

- src/langs/json/en.json
- src/lib/api/documents.test.ts
- src/lib/api/documents.ts
- src/lib/components/forms/Edit.svelte
- src/lib/components/forms/Reprocess.svelte
- src/lib/components/forms/stories/Edit.stories.svelte
- src/lib/components/inputs/Field.svelte
- src/lib/components/inputs/Text.svelte
- src/lib/components/inputs/TextArea.svelte
- src/lib/components/inputs/stories/Textarea.stories.svelte
- src/lib/components/layouts/Modal.svelte
- src/routes/documents/[id]-[slug]/+page.server.ts
- src/routes/documents/[id]-[slug]/sidebar/Actions.svelte
- src/routes/documents/[id]-[slug]/sidebar/DocumentMetadata.svelte
- src/style/kit.css
Closes #570 
Note that this is only for a single document. Bulk editing will probably be slightly different.
> Edit a document from the viewer

- src/lib/api/documents.ts
- src/lib/api/types.d.ts
I didn't have a chance to suggest these changes on #575, so here they are! Small potatoes. :potato:
> Small post-PR-merge tweaks

- package.json
- src/langs/json/en.json
- src/lib/api/documents.test.ts
- src/lib/api/documents.ts
- src/lib/components/common/Button.svelte
- src/lib/components/common/stories/Button.stories.svelte
- src/lib/components/forms/ConfirmDelete.svelte
- src/lib/components/forms/stories/ConfirmDelete.stories.svelte
- src/lib/components/layouts/Modal.svelte
- src/routes/app/+page.svelte
- src/routes/app/+page.ts
- src/routes/documents/[id]-[slug]/+page.server.ts
- src/routes/documents/[id]-[slug]/sidebar/Actions.svelte
> Delete document from the viewer

- src/langs/json/en.json
- src/lib/api/fixtures/documents/examples/the-santa-anas.json
- src/lib/components/common/Button.svelte
- src/lib/components/forms/EditData.svelte
- src/lib/components/forms/EditSections.svelte
- src/lib/components/forms/stories/EditData.stories.svelte
- src/lib/components/inputs/KeyValue.svelte
- src/lib/components/inputs/Select.svelte
- src/lib/components/inputs/stories/KeyValue.stories.svelte
- src/routes/documents/[id]-[slug]/+page.server.ts
- src/routes/documents/[id]-[slug]/sidebar/Data.svelte
Data and tag input, using `svelte-select` to choose or create keys (with the hope that this makes normalizing easier).
Might just merge this into #583 and review the whole thing at once.
> sveltekit data tag input

- .gitignore
- README.md
- embeds.js
- package-lock.json
- package.json
- src/embed/documentLoader.js
- src/embed/enhance.js
- src/embed/noteLoader.js
- src/embed/projectLoader.js
Does what it says on the tin. Trying for the simplest available solution here.
> build legacy embed scripts with esbuild

- src/langs/json/en.json
- src/lib/components/accounts/tests/__snapshots__/Mailkey.test.ts.snap
- src/lib/components/common/Button.svelte
- src/lib/components/common/Card.svelte
- src/lib/components/common/Field.svelte
- src/lib/components/common/FieldLabel.svelte
- src/lib/components/common/Tab.svelte
- src/lib/components/common/stories/Tab.stories.svelte
- src/lib/components/documents/CustomizeEmbed.svelte
- src/lib/components/documents/Note.svelte
- src/lib/components/documents/PDFPage.svelte
- src/lib/components/documents/Share.svelte
- src/lib/components/documents/stories/CustomizeEmbed.stories.svelte
- src/lib/components/documents/stories/Share.stories.svelte
- src/lib/components/documents/tests/Share.test.ts
- src/lib/components/inputs/Select.svelte
- src/lib/components/inputs/Text.svelte
- src/lib/components/inputs/TextArea.svelte
- src/lib/components/layouts/Modal.svelte
- src/lib/utils/embed.ts
- src/lib/utils/storage.ts
- src/lib/utils/tests/__snapshots__/embed.test.ts.snap
- src/lib/utils/tests/embed.test.ts
- src/lib/utils/tests/storage.test.ts
- src/routes/(embed)/documents/[id]/+layout.ts
- src/routes/(embed)/documents/[id]/+page.svelte
- src/routes/(embed)/documents/[id]/+page.ts
- src/routes/documents/[id]-[slug]/sidebar/Actions.svelte
Closes #563
Rebuilds our document share dialog for SvelteKit.
> Share dialog

- src/api/project.ts
- src/projects/Browser.svelte
- src/projects/Filters.svelte
- src/projects/ProjectList.svelte
- src/projects/ProjectListItem.svelte
- src/projects/ProjectPin.svelte
This opens up public projects to search via the UI. (Projects were always searchable via the API.)
> Allow searching of public projects

- .gitignore
- jsconfig.json
- src/api/types/orgAndUser.ts
- src/langs/json/en.json
- src/lib/api/feedback.ts
- src/lib/components/accounts/UserAvatar.svelte
- src/lib/components/accounts/UserMenu.svelte
- src/lib/components/accounts/stories/UserAvatar.stories.svelte
- src/lib/components/accounts/tests/__snapshots__/UserMenu.test.ts.snap
- src/lib/components/forms/UserFeedback.svelte
- src/lib/components/forms/stories/UserFeedback.stories.svelte
- src/lib/components/layouts/MainLayout.svelte
- src/lib/components/layouts/Toaster.svelte
- src/routes/+page.server.ts
- src/test/fixtures/accounts.ts
- src/test/handlers/feedback.ts
- tsconfig.json
- tsconfig.test.json
Closes #593
This adds a feedback form for users of the public preview to send us comments, bug reports, and ask questions. The form submits data to Baserow.
NOTE:
This depends upon two environment secrets to be updated in Netlify: `BASEROW_API_TOKEN` and `BASEROW_FEEDBACK_TABLE`. I can provide values for them. Without these values, submitting feedback will produce an error.
In Storybooks, we mock the Baserow API for testing success, error, and loading responses.
> Adds Feedback form

- src/config/production.js
- src/routes/app/+page.ts
- src/routes/documents/projects/+page.ts
Part of #597 
This tells the frontend where it lives in production, and also redirects `/app` to `/`.
Might do more on this branch as needed.
> Set prod domain to www.next.documentcloud.org

- src/routes/(pages)/home/+page.svelte
> Go to / not /documents/

- package-lock.json
- package.json
- public/mockServiceWorker.js
- src/hooks.client.ts
- src/hooks.server.ts
- src/lib/components/documents/Notes.svelte
- src/lib/components/documents/PDF.svelte
- src/lib/components/documents/PDFPage.svelte
- src/routes/documents/[id]-[slug]/+page.ts
> Use legacy build for PDF.js

- src/lib/components/documents/CustomizeEmbed.svelte
- src/lib/components/documents/PDF.svelte
- src/lib/components/documents/SelectMode.svelte
- src/lib/components/documents/Viewer.svelte
- src/lib/components/documents/toolbars/AnnotationToolbar.svelte
- src/lib/components/documents/toolbars/RedactionToolbar.svelte
- src/lib/components/forms/ConfirmRedaction.svelte
- src/routes/(embed)/documents/[id]/+layout.svelte
- src/routes/documents/[id]-[slug]/+page.svelte
Setting the value of `$currentMode` using a reactive statement lets us use links to update mode everywhere.
> Simplify currentMode state so it only flows in one direction

- src/lib/components/layouts/SidebarLayout.svelte
- src/style/kit.css
> Fix z-index of drawers

- src/langs/json/en.json
- src/lib/components/forms/UserFeedback.svelte
- src/lib/components/layouts/Error.svelte
- src/lib/components/layouts/stories/Error.stories.svelte
- src/routes/+error.svelte
Fixes #442
- Provides slots for reporting status code, error message, and providing actionable next steps.
- Provides a quick action to report a problem using our UserFeedback from.
> Adds an Error layout for +error.svelte pages

- src/langs/json/en.json
- src/lib/components/projects/ProjectActions.svelte
> Adds project upload and permission checks to Project Actions

- src/lib/components/projects/Collaborators.svelte
- src/lib/components/projects/ProjectActions.svelte
- src/lib/utils/permissions.ts
- src/routes/(app)/documents/projects/+page.svelte
Hit a 500 when browsing anonymously.
> Fix unguarded property lookups that were crashing the site

- src/lib/components/accounts/UserMenu.svelte
- src/lib/components/accounts/tests/__snapshots__/UserMenu.test.ts.snap
- src/lib/components/addons/tests/__snapshots__/AddOnsNavigation.test.ts.snap
- src/lib/components/layouts/stories/AppLayout.stories.svelte
- src/lib/components/navigation/LanguageMenu.svelte
- src/lib/components/navigation/OrgMenu.svelte
- src/lib/components/sidebar/SidebarItem.svelte
Some styling errors were introduced in #698. This resolves them.
- Reduce gap between start/end slots when no default slot
- Fix OrgMenu rendering
> Fixes for nav items

- static/robots.txt
> robots.txt

- src/lib/api/accounts.ts
- src/lib/components/addons/Scheduled.svelte
- src/lib/components/forms/AddOnDispatch.svelte
- src/lib/components/layouts/AddOnLayout.svelte
- src/lib/utils/search.ts
- src/lib/utils/tests/permissions.test.ts
- src/routes/(app)/add-ons/[owner]/[repo]/+page.svelte
Fixes errors encountered on add-on pages reported in [Sentry](https://muckrock.sentry.io/share/issue/05bfe6343ce74e36ab717f6594615a57/)
Progress towards #704
> Fixes undefined and null access errors

- src/routes/(app)/add-ons/+error.svelte
- src/routes/(app)/add-ons/[owner]/[repo]/+error.svelte
- src/routes/(app)/documents/+error.svelte
- src/routes/(app)/documents/[id]-[slug]/+error.svelte
- src/routes/(app)/projects/+error.svelte
- src/routes/(app)/projects/[id]-[slug]/+error.svelte
- src/routes/(app)/upload/+error.svelte
> Adds `+error.svelte` to major routes

- src/lib/components/forms/Search.svelte
- src/routes/(app)/projects/+page.svelte
- src/routes/(app)/projects/+page.ts
- **Fix public project search**
- **Use new API filters**
Closes #734
> Fix project search

- src/lib/components/navigation/HelpMenu.svelte
> Add donate button

- src/routes/(app)/projects/+page.server.ts
- src/routes/(app)/projects/[id]-[slug]/+page.ts
Fixes #740
Fixes 137b42ec36774612873907d28a9d8340
> Adds `csrf_token` to project route data

- src/lib/components/forms/AddOnDispatch.svelte
Fixes #739
Fixes ba6558d74e034d76bf788ba9202972b6
> Checks `AddOnDispatch.required` before access

- src/lib/api/accounts.ts
- src/lib/api/addons.ts
- src/lib/api/documents.ts
- src/lib/api/embed.ts
- src/lib/api/flatpages.ts
- src/lib/api/notes.ts
- src/lib/api/projects.ts
- src/lib/api/tests/addons.test.ts
- src/lib/api/tests/projects.test.ts
- src/lib/components/addons/History.svelte
- src/lib/components/addons/Scheduled.svelte
- src/lib/components/common/Toast.svelte
- src/lib/components/documents/ResultsList.svelte
- src/lib/utils/api.ts
- **Catch all server-side fetch calls so the site doesn't crash**
- **Catch client-side fetches**
Should close #761
> Catch all the fetches

- src/common/Pin.svelte
- src/lib/components/projects/ProjectPin.svelte
Closes #762 
Does what it says on the tin.
> Disable project pin if project.edit_access is false

- src/lib/api/embed.ts
- src/lib/api/tests/embed.test.ts
- src/routes/(app)/documents/[id]-[slug]/+layout.svelte
- src/routes/(app)/projects/[id]-[slug]/+page.svelte
- src/routes/(app)/upload/+layout.svelte
> Clean up oembed code and add to project pages

- src/lib/components/layouts/Navigation.svelte
- src/routes/(pages)/home/+page.svelte
- src/routes/(pages)/home/+page.ts
> Set next param on signin

- src/common/MenuInsert.svelte
- src/langs/json/en.json
- src/lib/api/accounts.ts
- src/lib/api/tests/accounts.test.ts
- src/lib/components/common/PlausibleTracker.svelte
- src/lib/components/layouts/Navigation.svelte
- src/lib/components/navigation/OrgMenu.svelte
- src/lib/components/navigation/stories/OrgMenu.stories.svelte
- src/pages/app/accounts/UserMenu.svelte
- src/test/handlers/accounts.ts
Fixes #763
- Clarifies dropdown language
- Hides org select and links to Squarelet if no other orgs
- Boost test coverage of `src/lib/accounts`
> Improve individual org menu appearance

- src/langs/json/en.json
- src/lib/components/forms/DocumentUpload.svelte
- src/lib/components/forms/tests/DocumentUpload.test.ts
- src/lib/components/inputs/Dropzone.svelte
- src/lib/components/inputs/File.svelte
- src/lib/components/inputs/Select.svelte
- src/lib/components/inputs/Switch.svelte
Fixes #523
- Adds support for pasting files
- Changes language and design of DocumentUpload form
- Changes styling of input components it uses
> Drop files anywhere on DocumentUpload form

- src/lib/components/onboarding/GuidedTour.svelte
Fixes #794
Assumes unauthenticated users don't give a hoot about the new UI and just want to get on with using the site
> Only show guided tour to signed-in users

- src/lib/utils/api.ts
> Catch JSON errors in API error response

- src/langs/json/en.json
- src/lib/components/forms/DocumentUpload.svelte
- src/lib/components/inputs/AccessLevel.svelte
- src/lib/components/inputs/stories/AccessLevel.stories.svelte
Addresses the issue in #842 (`access` was null).
There may be other upload issues, but this is what I can see.
> Ensure access is set on uploads

- src/lib/components/common/KV.svelte
- src/lib/components/common/stories/KV.stories.svelte
Fixes #830
Adds story for long value in a constrained container
> Handle overflowing tag contents

- src/lib/components/forms/UploadListItem.svelte
- src/lib/components/forms/stories/DocumentUpload.stories.svelte
- src/lib/components/inputs/Field.svelte
> Handle long document names when uploading

- src/lib/components/common/AddOns.svelte
- src/lib/components/common/stories/AddOns.stories.svelte
- src/lib/components/layouts/Project.svelte
- src/routes/(app)/documents/+page.svelte
- src/routes/(app)/projects/[id]-[slug]/+page.ts
> Pass query to add-on dispatch

- src/lib/components/viewer/Page.svelte
- src/lib/components/viewer/Viewer.svelte
Does what it says on the tin. Closes #883
> Hide page actions on embeds

- src/routes/(app)/projects/+page.svelte
> Adds sidebar toggles to project list header

- src/config/production.js
> Production URLs

- src/langs/json/en.json
- src/lib/components/documents/Share.svelte
- src/lib/components/documents/stories/Share.stories.svelte
- src/lib/components/projects/ProjectShare.svelte
- src/lib/utils/copy.ts
- src/lib/utils/tests/copy.test.ts
Fixes #937
- Refactors clipboard access into tested utility function
> Guard against failures to access clipboard 

- src/routes/+layout.ts
> Guard against localStorage access errors

- src/lib/components/sidebar/ViewerActions.svelte
> When sharing, default page to the viewer's current page

- src/lib/components/forms/AddOnDispatch.svelte
- src/lib/components/forms/stories/AddOnDispatch.stories.svelte
> Prefill add-on fields from query params

- src/embed/iframeSizer.js
- src/lib/components/documents/Share.svelte
- src/lib/components/documents/tests/Share.test.ts
- src/routes/embed/documents/[id]/pages/[page]/+page.svelte
- tsconfig.json
- Fixes #960 by setting default height & width on iframes
- Fixes auto-sizing of legacy iframes using `enhance.js`
> Embed Fixes

- src/lib/components/documents/Share.svelte
- src/lib/components/projects/ProjectShare.svelte
> iframes are not self-closing

- src/lib/components/projects/ProjectShare.svelte
No options on this yet, just 100% width and 600 px tall.
> Add default size to project embed

- src/lib/components/projects/ProjectShare.svelte
> Improve display of short project share dialogs

- src/lib/components/viewer/Note.svelte
- src/lib/components/viewer/ViewerContext.svelte
- src/routes/embed/documents/[id]/annotations/[note_id]/+page.svelte
> Renders new note component onto note embed pages

- src/langs/json/en.json
- src/langs/json/es.json
- src/langs/json/fr.json
- src/langs/json/it.json
Simple change to language.
To view, open the preview deployment and select the "Feedback" action from the top navigation.
> Removes Beta language from Feedback dialog

- src/lib/components/forms/DocumentUpload.svelte
> Catch navigation when loading, not when NOT loading

- src/langs/json/en.json
- src/lib/components/common/ShowSize.svelte
- src/lib/components/common/tests/ShowSize.demo.svelte
- src/lib/components/common/tests/ShowSize.test.ts
- src/lib/components/forms/ConfirmDelete.svelte
- src/lib/components/forms/EditDataMany.svelte
- src/lib/components/forms/EditMany.svelte
- src/lib/components/forms/Projects.svelte
- src/lib/components/forms/stories/ConfirmDelete.stories.svelte
- src/lib/components/forms/stories/EditData.stories.svelte
- src/lib/components/forms/stories/Projects.stories.svelte
- src/routes/(app)/documents/+page.server.ts
> Bulk editing limit for projects, deletes and data

- src/routes/embed/projects/[project_id]-[slug]/+page.ts
Maybe fixes #1053 
This potentially makes an extra fetch, but only if the first try fails.
> Try fetching project first, then retry with old pattern

- public/mockServiceWorker.js
- src/lib/components/addons/Scheduled.svelte
- src/lib/components/addons/ScheduledEvent.svelte
- src/lib/components/forms/AddOnDispatch.svelte
- src/lib/components/layouts/AddOnLayout.svelte
- src/routes/(app)/add-ons/[owner]/[repo]/[event]/+page.svelte
Closes #853 
Two things to fix this:
- On navigation, set the tab to `dispatch`
- Update the `$values` store using `data`
> Set initial form values from page data

- package-lock.json
- src/langs/json/en.json
- src/lib/components/accounts/tests/__snapshots__/Mailkey.test.ts.snap
- src/lib/components/accounts/tests/__snapshots__/UserMenu.test.ts.snap
> Fix capitalization

- .github/workflows/chromatic.yml
- package-lock.json
- public/mockServiceWorker.js
- src/lib/components/addons/History.svelte
- src/lib/components/addons/HistoryEvent.svelte
- src/lib/components/addons/stories/HistoryEvent.stories.svelte
- src/lib/components/addons/tests/__snapshots__/AddOnListItem.test.ts.snap
- src/lib/components/processing/AddOns.svelte
- src/lib/components/processing/Documents.svelte
- src/lib/components/processing/Process.svelte
- src/lib/components/processing/stories/Process.stories.svelte
- src/test/fixtures/addons.ts
Closes #1062 
The `<Process>` component is more of a wrapper now, and gets used in `<HistoryEvent>`, so we can show run progress on the dispatch. And now `<HistoryEvent>` gets used in the process dropdown, so files and messages are available globally.
> Unify add-on run components and simplify process wrapper

- src/lib/components/documents/Header.svelte
> Break on words, not characters

- static/robots.txt
https://developers.cloudflare.com/fundamentals/reference/cdn-cgi-endpoint/
> Disallow: /cdn-cgi/

- src/lib/components/forms/ConfirmDelete.svelte
> Handle type: redirect result value

- src/lib/components/viewer/Text.svelte
Closes #1072 
Test: https://deploy-preview-1106.muckcloud.com/documents/20010802-sd191/?mode=text
> Use text-wrap balance instead of pretty

- src/embed/enhance.js
- src/embed/noteLoader.js
- src/embed/projectLoader.js
- src/lib/api/documents.ts
- src/lib/components/documents/Share.svelte
- **Page and note embeds don't have slugs. Flip project ID and slug.**
- **Page embeds use EMBED_URL**
Closes #1103 
Closes #918
> Fixes for legacy embed scripts and page embeds

- src/lib/components/documents/Share.svelte
Does what it says on the tin. Closes #1112
> Allow fullscreen on document embeds

- package-lock.json
- src/routes/embed/documents/[id]/annotations/[note_id]/+page.svelte
Just in case `onload` has already fired when we call `informSize`.
> Track size in onMount
