src/api/document.js

I want to turn highlighting off by default so API users aren't using it by default, making things quicker.  This just turns highlighting on explicitly for the frontend.

explicitly turn highlighting on in frontend

---

src/pages/app/Documents.svelte

The front login page now checks if you have the verified journalist tag on your account needed for upload before showing a draggable highlight in the drop area. This should draw the user's attention to the warning there of what they can do.

Fix draggable so no highlight when unverified

---

src/langs/json/en.json
src/pages/app/Documents.svelte

An unverified user sees a new call to action button: 
It opens a new tab to: https://www.muckrock.com/assignment/request-account-verification-377/form/
Should this string of this URL be localized?
A verified user doesn't see any change: <img width="1079" alt="image" src="https://user-images.githubusercontent.com/283343/152819746-7a5e9c2f-37da-4156-beb8-8c098820e9f3.png">

Verify button call to action

---

README.md

Because output redirection is a service offered by the command-line
interpreter, the `sudo` utility has no effect on its permissions. Use
the `pipe` utility (available on by default on GNU/Linux and macOS
systems) to guarantee that the "write" operation described by this
instruction runs with administrative privileges.

Correct command require privilege escalation

---

src/pages/FlatPage.svelte

Updated Svelte doesn't allow selectors like `:global(h5, h6)`, so this splits them.

Fix global selectors on FlatPage.svelte

---

package-lock.json
package.json
src/common/Draggable.svelte
src/common/ProgressiveImage.svelte
src/pages/app/sidebar/ProjectFilters.svelte

A lot of nested rules in Sass were being marked as unused. I un-nested them so they'd get wrapped in `:global()` properly.

Fix selectors so Svelte knows they're used

---

src/pages/app/App.svelte
src/pages/app/sidebar/OrgUsers.svelte
src/pages/viewer/Viewer.svelte

Does what it says on the tin.
I'm adding our Plausible script tag in <svelte:head> wrapped in a login check. This just sends pageviews right now. Will add event tracking if we like this approach.
We don't load the script if you're not logged in, or if you're in an embed.

Add plausible to App and Viewer for logged-in users

---

src/pages/app/App.svelte
src/pages/viewer/Viewer.svelte

This replaces the slug in a document URL with `obscure`, so `/documents/23702579-boston_covid-19_vaccination_report_10may2021` looks like `/documents/23702579-obscure` in the analytics dashboard.

Obscure document slugs in analytics for privacy

---

src/pages/app/App.svelte
src/pages/viewer/Viewer.svelte

This replaces the slug in a document URL with `obscure`, so `/documents/23702579-boston_covid-19_vaccination_report_10may2021` looks like `/documents/23702579-obscure` in the analytics dashboard.

Production: Obscure document slugs in analytics for privacy

---

src/Main.svelte
src/common/dialog/AddonBrowserDialog.svelte
src/common/dialog/AddonDispatchTsDialog.svelte
src/manager/addons.js
src/manager/layout.js
src/pages/app/App.svelte
src/pages/app/menus/AddonsMenu.svelte
src/router/router.js
src/routes.js
src/structure/addon.js

Adds hash URLs to `App.svelte`, based on this plan: https://www.notion.so/muckrock/Add-On-deep-linking-fe36e206f06146c4aa1a340f23d33ec3
Still to do: Pre-filling the add-on dispatch form based on query params, but that'll be next.
Try locally:
- https://www.dev.documentcloud.org/app#add-ons/MuckRock/Klaxon/1
- https://www.dev.documentcloud.org/app#add-ons/MuckRock/Klaxon
- https://www.dev.documentcloud.org/app#add-ons

add on routing

---

src/common/dialog/AddonDispatchTsDialog.svelte
src/manager/layout.js
src/pages/app/App.svelte

Load this URL locally: https://www.dev.documentcloud.org/app?q=%2Buser%3Achris-100000%20&site=https://www.muckrock.com/&selector=*#add-ons/MuckRock/Klaxon
That will load the app with the Add-On dispatch open to Klaxon, with the `site` and `selector` fields pre-populated. Any fields defined in `schema.properties` can be pre-filled. Anything else gets filtered out.

Load initial add-on dispatch values from querystring

---

src/api/addon.js
src/common/dialog/AddonDispatchTsDialog.svelte
src/manager/addons.js
src/pages/app/App.svelte

This uses the `repository` filter to fetch one, and only one, add-on in the dispatch dialog. No more looping through.

Use that new API filter

---

src/router/router.js

This was causing search errors when the modal closed.

Trim search params to avoid encoding errors

---

src/common/dialog/AddonDispatchTsDialog.svelte

`window.structuredClone` isn't available on older firefox

Old FF fix

---

src/Main.svelte
src/api/addon.js
src/common/AddonRun.svelte
src/common/Dropdown.svelte
src/common/dialog/AddonBrowserDialog.svelte
src/common/dialog/AddonDispatchTsDialog.svelte
src/common/dialog/DiagnosticDialog.svelte
src/langs/json/en.json
src/manager/addons.js
src/manager/documents.js
src/manager/layout.js
src/pages/app/AddonStatus.svelte
src/pages/app/App.svelte
src/pages/app/menus/AddonsMenu.svelte
src/pages/app/sidebar/Sidebar.svelte
src/router/router.js
src/routes.js
src/structure/addon.js

Lots happening here:
- Formatting and cleanup some unused imports
- Hash URLs mostly working
- loading events
- Maybe finally getting state right
- un-sass
- Load initial values from querystring
- Use that new API filter
- Handle anonymous users linking to add-ons
- Cleanup URL on close
- remove a console.log
- Trim params
- structuredClone isn't available on older firefox
See it working on staging: https://www.staging.documentcloud.org/app?q=%2Buser%3Afreeuser-100013&site=https://www.muckrock.com#add-ons/MuckRock/documentcloud-scraper-addon
That will open the Add-On dispatch dialog with the `site` field pre-filled. Any add-on properties present in the querystring become initial values in the form, so this will help with Klaxon and probably other add-ons. When you close the modal, we …

Production push: Add-on deep linking

---

src/api/addon.js
src/common/dialog/AddonBrowserDialog.svelte
src/manager/addons.js

Made API methods with more than two arguments take destructured objects instead of positional arguments, and fixed calls as needed.

Fix API calls for add-on pagination

---

src/addons/dispatch/Form.svelte
src/addons/dispatch/fields/Text.svelte

Text fields were defaulting to an empty string, and that was tripping up validation. This should fix that issue.

Set text fields null when blank and filter out nulls

---

src/Main.svelte
src/addons/browser/AddOnList.svelte
src/addons/browser/AddOnListItem.svelte
src/addons/browser/stories/AddOnListItem.stories.svelte
src/addons/browser/stories/Browser.stories.svelte
src/addons/dispatch/Dispatch.svelte
src/addons/fixtures/addons-active.json
src/addons/runs/ScheduledEvent.svelte
src/addons/sidebar/AddonListItem.svelte
src/addons/sidebar/ListItem.svelte
src/addons/sidebar/Sidebar.svelte
src/addons/sidebar/stories/ListItem.stories.svelte
src/addons/sidebar/stories/Sidebar.stories.svelte
src/addons/stories/Sidebar.stories.svelte
src/langs/json/en.json
src/pages/app/sidebar/Project.svelte
src/pages/app/sidebar/Projects.svelte
src/pages/app/sidebar/Sidebar.svelte

See it on staging: https://www.staging.documentcloud.org/app?q=
- Make projects in sidebar collapsible to accomodate pinned add-ons
- Use a single addon property for AddOnListItem, like everything else
- Populate the addon sidebar
- Coordinate between sidebar and browser
- Update src/addons/sidebar/Sidebar.svelte
- Update src/addons/sidebar/Sidebar.svelte
- Use icon instead of full pin component
- Styling for sidebar

Production push: addon sidebar

---

src/main.js

Switched to a dynamic import so we don't have any Sentry code on embeds.

Don't load Sentry on embeds

---

src/main.js

Check in the console for `__SENTRY__` [in the viewer](https://www.staging.documentcloud.org/documents/20005908-finalseasonal_allergies_pollen_and_mold_2023__en) vs [embed](https://www.staging.documentcloud.org/documents/20005908-finalseasonal_allergies_pollen_and_mold_2023__en?embed=1).

No Sentry on embeds

---

.storybook/main.ts
package-lock.json
package.json
public/mockServiceWorker.js
src/addons/browser/stories/AddOnListItem.demo.svelte
src/addons/browser/stories/AddOnListItem.stories.svelte
src/addons/browser/stories/Filter.demo.svelte
src/addons/browser/stories/Filter.stories.svelte
src/addons/browser/stories/SearchInput.demo.svelte
src/addons/browser/stories/SearchInput.stories.svelte
src/addons/dispatch/stories/Form.demo.svelte
src/addons/dispatch/stories/Form.stories.svelte
src/addons/dispatch/stories/Header.demo.svelte
src/addons/dispatch/stories/Header.stories.svelte
src/addons/dispatch/stories/ScheduledInset.stories.svelte
src/addons/sidebar/stories/ListItem.demo.svelte
src/addons/sidebar/stories/ListItem.stories.svelte
src/addons/sidebar/stories/Sidebar.demo.svelte
src/addons/sidebar/stories/Sidebar.stories.svelte
src/addons/stories/Drawer.demo.svelte
src/addons/stories/Drawer.stories.svelte
src/addons/stories/Paginator.demo.svelte
src/addons/stories/Paginator.stories.svelte

Closes #242 
This deals with a bug in Storybook (https://github.com/storybookjs/addon-svelte-csf/issues/145) that causes Svelte stories to break when there's any extra HTML in the `<Template>` or `<Story>` slot. Apparently it's fixed in the latest version, but we can't use it until we can upgrade to Svelte 4.
The temporary solution is to add demo components, like `AddOnListItem.demo.svelte`, next to stories. Those demo components contain all the markup we need and pass arguments through. It's a hack, but it works.

Add demo components to wrap stories that need extra HTML

---

src/api/session.js

Partially undoes #319 but in a way that redirects based on a location header, instead of hostname. 
Example document, private to MuckRock: https://deploy-preview-322.muckcloud.com/documents/20006188-change-assessment_w_mjw-letter
Closes #321

Maybe handle redirects manually"

---

src/addons/AddOnPin.svelte
src/addons/browser/AddOnList.svelte
src/addons/browser/AddOnListItem.svelte
src/addons/browser/Browser.svelte
src/addons/dispatch/Dispatch.svelte
src/addons/dispatch/Header.svelte
src/addons/dispatch/ScheduledInset.svelte
src/addons/dispatch/stories/Dispatch.stories.svelte
src/addons/runs/HistoryEvent.svelte
src/addons/runs/ScheduledEvent.svelte
src/addons/sidebar/AddonListItem.svelte
src/addons/sidebar/Sidebar.svelte
src/addons/types.ts
src/pages/app/menus/AddonsMenu.svelte

Closes #250
This provides a control to pin/unpin an add-on from its detail page. Since pinned add-ons in the application sidebar link to the detail page, this provides users a simple path to unpinning an add-on.
This update refactors an `AddOnPin` component and `pinned` store out of the AddOnListItem. It also extracts the types to a standalone file.

Adds Pin controller to Add-On Detail page

---

src/addons/dispatch/fields/Number.svelte

Closes #318 
See JSON schema: https://json-schema.org/understanding-json-schema/reference/numeric#number

JSON schema uses minimum and maximum, not min and max

---

jest.config.js
package-lock.json
package.json
preprocess.config.js
src/api/orgAndUser.js
src/api/session.js
src/manager/caching.test.js
src/manager/manager.js
src/viewer/document.js
src/viewer/modification/modification.js
svelte.config.js
webpack.app.config.js
webpack.base.config.js
webpack.config.js
webpack.embed.config.js

This is branched from #331, so that should merge first.
- Switch to the version of Svue hosted in the MuckRock org on Github
- Add a `svelte.config.js` file and tell Jest how to handle Svelte, TypeScript and Sass

Unit tests

---

.gitignore
Makefile
deploy-to-netlify.sh
public/_headers
public/_redirects
src/common/Dropdown.svelte
src/pages/app/App.svelte
src/pages/viewer/Viewer.svelte
webpack.app.config.js
webpack.base.config.js

Everything webpack builds should end up under `public/assets`, except for `public/index.html`.
This also keeps static assets out of the client side router, so a 404 like https://deploy-preview-337.muckcloud.com/assets/foo.js won't get rendered as HTML (and therefore not cached).

Namespace built assets to make caching easier

---

src/addons/dispatch/Selection.svelte
src/addons/dispatch/fields/ArrayField.svelte
src/api/document.js
src/pages/FlatPage.svelte
tests/README.md
tests/anonymous/manager/app.spec.js
tests/anonymous/pages/home.spec.js
tests/anonymous/viewer/document.spec.js

- Catch invalid selector in FlatPage.svelte
- Add more tests for the manager view

More tests

---

package-lock.json
src/addons/dispatch/fields/ArrayField.svelte

Closes #358 
Sometimes the `value` property on `ArrayField` gets set to `undefined` and that breaks things that assume it's an array.

Ensure ArrayField value is always an array

---

src/addons/progress/AddonRun.svelte
src/addons/progress/AddonStatus.svelte
src/manager/documents.js
src/pages/home/Home.svelte
src/util/visibility.js
src/viewer/document.js

- Handle an undefined
- Better error messaging
- Catch more undefined things

Catch type errors where we can

---

.storybook/preview.ts
package-lock.json
package.json
src/common/stories/Calendar.stories.ts

This adds a Storybook date decorator for setting the "now" time when rendering components. This prevents the story snapshots from changing in Chromatic and requiring re-approval.
The date on the Calendar storybook should be set to 12/5/23 @ 11:00 in this PR and in perpetuity.

Update Calendar to fixed "now" date for snapshots

---

src/common/dialog/SearchTipsDialog.svelte
src/common/dialog/stories/SearchTipsDialog.stories.svelte
src/common/stories/ErrorData.stories.svelte
src/common/stories/HtmlField.stories.svelte
src/common/stories/Logo.stories.svelte

This adds four more components into Storybook. These all depend on the router, so my goal is to figure out whether we can make them stateless. 
`src/common/dialog/SearchTipsDialog.svelte` had one `Link` component, which is now an `a` tag. It still relies on the `orgsAndUsers` store in order to check if the current user is logged in, and use that to write an example search.
`src/common/ErrorData.svelte` uses the `nav` helper to turn route names into URLs.
`src/common/Logo.svelte` has a surprising amount of logic in it. This should really just be an icon that gets wrapped in a link, and that logic should be outside the component.
`src/common/HtmlField.svelte` gets used in the viewer, as text entry. Will probably make a new version in SvelteKit when we have more form handling options. …

More common components into Storybook

---

src/addons/dispatch/Form.svelte
src/addons/dispatch/fields/Select.svelte
src/addons/dispatch/fields/index.js
src/addons/fixtures/addons.json

Any field with `"type": "string"` and `"enum: [...]"` set will now get a `<select>` input instead of a text field.
Closes #400

Use select input for text fields with enum property

---

.github/workflows/coverage.yml
.gitignore
jest.config.js
package-lock.json
package.json
src/api/test/fixtures/empty.ts
src/api/test/fixtures/project.ts

Adds support for writing test files written in and which reference TypeScript
In order to better understand the reliability of test files, it's helpful to have coverage generated as part of running tests.
With IDE extensions like [Coverage Gutters](https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters), it's easy to see which areas of a function have coverage.
The workflow will comment on opened PR with their current coverage level. This is an important signal into the overall health and quality of our codebase. If we provide coverage regression checks as part of PR review, this is a way to begin to lever up the codebase's overall coverage.
If everything works as expected, this PR should recieve an automated comment with its coverage level.

Testing improvements

---

.github/workflows/chromatic.yml

Chromatic's [TurboSnap](https://www.chromatic.com/docs/turbosnap/) feature only builds stories related to changed files. This helps reduce our overall usage of the service and speeds up our PR testing.

Setup Chromatic with TurboSnap for optimized deployments

---

.storybook/main.ts
.storybook/preview.ts
package-lock.json
package.json
src/api/orgAndUser.js
src/common/dialog/stories/RevisionsDialog.stories.svelte

A recent change removed the CSRF token check during the call to the `getMe` API handler. This led to increased unauthenticated calls to getMe from the embedded viewer. This reintroduces that check and should minimize unnecessary requests to the endpoint.

Prevent calls to `getMe` from embed

---

src/config/config.js

Fixes issue with old documents not having extra large images.
Visible on staging (last PR, without this fix): https://deploy-preview-417.muckcloud.com/documents/20000254-doc_3-copy-53
Production: https://www.documentcloud.org/documents/4488414-Edison-Electric-Institute-2004-2

Sort image sizes smallest to biggest

---

jsconfig.json
package.json
src/lib/api/documents.js
src/lib/api/types.d.ts
src/lib/api/users.js
src/routes/+layout.js
src/routes/+layout.svelte
src/routes/app/+layout.js
src/routes/app/+page.svelte
src/routes/documents/[id]-[slug]/+layout.js
src/routes/documents/[id]-[slug]/+layout.svelte
src/routes/documents/[id]-[slug]/+page.js
src/routes/home/+page.svelte
tsconfig.json

This adds stub routes and some loading functions to the SvelteKit branch. Doesn't look like much at the moment, but this sets us up to get things on the page.
This is using the plan sketched out in #431, so there are more routes than we have on the current site. In particular, I've tried to break functionality into dedicated routes, using layouts for common UI and data loading. For example, if you want to modify a document, you go to `/documents/<id>/modify/` and we load the extra UI layer there. If you're at `/documents/<id>/`, we know you're only viewing and we don't need to check what else you might do.
Additionally, there are some API helper methods and Typescript types here. These have some overlap with the current site, so I've kept them in `src/lib` to avoid conflicts. This can all …

SvelteKit: Stub routes

---

src/common/tests/Paginator.test.ts
src/lib/components/common/Button.svelte
src/lib/components/common/Checkbox.svelte
src/lib/components/common/PageToolbar.svelte
src/lib/components/common/stories/Button.stories.svelte
src/lib/components/common/stories/Checkbox.stories.svelte
src/lib/components/common/stories/KV.stories.svelte
src/lib/components/common/stories/PageToolbar.stories.svelte
src/lib/components/common/tests/Button.test.ts
vite.config.js
vitest-setup.js

- Button
- Checkbox
- PageToolbar

sveltekit components

---

src/pages/app/Document.svelte
src/pages/app/stories/DocumentThumbnail.stories.svelte
src/structure/project.js
src/structure/searchParams.js

Fix for project embeds. Imports were missing (and maybe always have been).
See it working here: https://deploy-preview-467.muckcloud.com/projects/scotus-200027/
OEmbed does not seem to work on staging, but I believe that's a separate issue.

Fix project embeds

---

src/pages/app/sidebar/projects/ProjectList.svelte
src/projects/Browser.svelte

The computed property was causing a recurring fetch.

Don't refetch pinned project list more than we need to

---

src/langs/json/en.json
src/pages/app/ActionBar.svelte
src/pages/app/ActionBarContainer.svelte
src/pages/app/Documents.svelte
src/pages/app/stories/ActionBar.stories.svelte

This closes #465 by adding a document count back to the ActionBar.
In the process of updating the component, I decoupled it from state with an itermediate ActionBarContainer.
I also updated some styling and created a Storybook for testing.
To review, please approve the new components in our Chromatic Storybook and examine the preview deployment for correct look and behavior.

Adds document count to ActionBar

---

package-lock.json
src/config/config.js
src/lib/api/documents.ts
src/lib/api/types.d.ts
src/lib/components/Search.svelte
src/lib/components/documents/ResultsList.svelte
src/lib/components/documents/stories/ResultsList.stories.svelte
src/routes/app/+page.svelte
src/routes/app/+page.ts
src/style/kit.css

Implements infinite scroll instead of pagination for search results.
Implements "select all" in the manager and shows result counts in the bottom action bar.
Try it here: https://deploy-preview-494.muckcloud.com/app/?q=boston

Infinite scroll for search results

---

.github/workflows/sveltekit.yml
.storybook/main.ts
jsconfig.json
src/lib/api/fixtures/mock.ts
src/routes/stories/project-embed.stories.svelte
vite.config.js

This improves reporting on any SvelteKit PRs by:
- Limiting Storybook to only SvelteKit directories, hopefully allowing Chromatic to successfully build and report changes.
- Limiting Vitest to only SvelteKit directories, to provide more helpful feedback on PR coverage changes.
- Limiting `check` to only check SvelteKit directories and related files, to flag any type errors during the PR process.
When I say SvelteKit directories, I mean `src/lib` and `src/routes`.
Check is currently failing since we have a number of unaddressed type and a11y issues. Those can be fixed in a follow-up task, but having the failing check will be a good reminder that they need to be fixed.

CI for SvelteKit PRs

---

src/pages/app/Documents.svelte

Corresponds to https://github.com/MuckRock/documentcloud/issues/203
I see that the airtable form also appears in a bunch of the .json files for translations. Do I have to manually add those in or will the build process change those for me?

Update airtable form link

---

src/langs/json/en.json
src/lib/api/fixtures/documents/highlight.json
src/lib/api/fixtures/documents/search-highlight.json
src/lib/api/types.d.ts
src/lib/components/documents/DocumentListItem.svelte
src/lib/components/documents/NoteHighlights.svelte
src/lib/components/documents/ResultsList.svelte
src/lib/components/documents/SearchHighlight.svelte
src/lib/components/documents/SearchHighlights.svelte
src/lib/components/documents/stories/NoteHighlights.stories.svelte
src/lib/components/documents/stories/ResultsList.stories.svelte
src/lib/components/documents/stories/SearchHighlights.stories.svelte
src/lib/components/documents/tests/ResultsList.test.ts
src/style/kit.css

This adds two components -- `SearchHighlights.svelte` and `NoteHighlights.svelte` -- that wrap respective highlights in a `details/summary` block for collapsing.
This very much needs a style pass.

Search highlights

---

src/langs/json/en.json
src/lib/components/common/KV.svelte
src/lib/utils/search.ts
src/lib/utils/tests/search.test.ts
src/routes/documents/[id]-[slug]/sidebar/Data.svelte
src/routes/documents/[id]-[slug]/sidebar/stories/Data.stories.svelte

This uses the existing `KV.svelte` component to render both tags and data in the viewer sidebar. Read-only for now.
Very minimal implementation, but this might be enough for now.
Example: https://deploy-preview-554.muckcloud.com/documents/20000353-miliaraki03/

Basic tag and KV rendering

---

src/lib/api/accounts.test.ts
src/lib/api/accounts.ts
src/lib/api/fixtures/documents/revisions.json
src/lib/api/types.d.ts
src/lib/components/common/Card.svelte
src/lib/components/documents/Revisions.svelte
src/lib/components/documents/stories/Revisions.stories.svelte
src/lib/components/forms/RevisionControl.svelte
src/lib/components/forms/stories/RevisionControl.stories.svelte
src/lib/components/inputs/Switch.svelte
src/premium-credits/UpgradePrompt.svelte
src/routes/documents/[id]-[slug]/+page.server.ts
src/routes/documents/[id]-[slug]/revisions/+page.svelte
src/routes/documents/[id]-[slug]/sidebar/Actions.svelte

Revision control, on its own URL route. Probably needs a little style help, but it works.

sveltekit revisions

---

src/lib/components/common/Portal.svelte
src/lib/components/layouts/MainLayout.svelte
src/lib/components/layouts/Modal.svelte
src/lib/components/layouts/Portal.svelte
src/lib/components/layouts/stories/MainLayout.stories.svelte
src/lib/components/layouts/stories/Modal.stories.svelte
src/routes/documents/[id]-[slug]/+layout.svelte
src/routes/documents/[id]-[slug]/redact/+page.svelte
src/routes/documents/[id]-[slug]/sidebar/Actions.svelte
src/routes/documents/[id]-[slug]/sidebar/DocumentMetadata.svelte

This renders Modals in a new `Portal` component, following the proposal made in #578. This approach to modals does not require global context or any state management. The parent calling component needs to simply track whether it wants the modal to be displayed, or not.
To fix:

Render Modals in Portals

---

src/langs/json/de.json
src/langs/json/en.json
src/langs/json/es.json
src/langs/json/fr.json
src/langs/json/ru.json
src/langs/json/uk.json
src/pages/app/accounts/HelpMenu.svelte

I added a link to https://www.muckrock.com/donate/ in the drop down with the correct icon. 
Clicking on the link locally leads to a page not found error, but the link is definitely there and clicking "Open link in new tab" works as expected. Going to see if different behavior happens during staging deploy

Adds donate page to help dropdown menu

---

src/lib/components/forms/EditSectionRow.svelte
src/lib/components/forms/EditSections.svelte
src/routes/documents/[id]-[slug]/annotate/+page.server.ts

Adds a new `EditSectionRow.svelte` component to wrap the logic for creating, updating and removing sections. This also deals with the problem of zero-indexed page numbers.

Fix section logic

---

src/lib/components/sidebar/SidebarGroup.svelte
src/lib/components/sidebar/stories/SidebarGroup.stories.svelte
src/routes/documents/[id]-[slug]/annotate/+page.svelte
src/routes/documents/[id]-[slug]/redact/+page.svelte
src/routes/documents/[id]-[slug]/sidebar/Actions.svelte
src/routes/documents/[id]-[slug]/sidebar/Data.svelte
src/routes/documents/[id]-[slug]/sidebar/Notes.svelte
src/routes/documents/[id]-[slug]/sidebar/Projects.svelte
src/routes/documents/[id]-[slug]/sidebar/Sections.svelte
src/routes/documents/sidebar/AddOns.svelte
src/routes/documents/sidebar/Projects.svelte

Add a unique `name` prop and the sidebar will remember its state.
```svelte
<SidebarGroup name="projects">
...
</SidebarGroup>
<SidebarGroup>
...
</SidebarGroup>
```
Closes #481

SidebarGroup can remember collapsed state

---

.storybook/decorators/TipOfDayContextDecorator.svelte
.storybook/preview.ts
src/lib/api/flatpages.ts
src/lib/api/types.d.ts
src/lib/components/common/TipOfDay.svelte
src/lib/components/documents/ResultsList.svelte
src/lib/components/layouts/MainLayout.svelte
src/routes/(embed)/stories/note-embed.stories.svelte
src/routes/(embed)/stories/page-embed.stories.svelte
src/routes/(embed)/stories/project-embed.stories.svelte
src/routes/+layout.svelte
src/routes/+layout.ts

Fixes #596
This loads the "Tip of the Day" flatpage content and renders it at the top of the main layout.
It now provides a "hide" action, which will keep the tip hidden as long as:
- the user keeps their browser's localStorage
- the tip's content hasn't changed
If there is a new tip from the last time a user hid it, the TipOfTheDay will reappear with the new information.

Display persistent messages in navigation 

---

package-lock.json
package.json
src/lib/components/common/PlausibleTracker.svelte
src/lib/components/layouts/AppLayout.svelte

Closes #630
This should only track pageviews on application routes for signed-in users.
To test, open the DevTools Network panel and check that pageview events are being sent to Plausible. Since we don't have a property set up for preview deployments or `next.www.documentcloud.org`, we don't see these events reported in the Plausible interface.
**Update** We now have a Plausible property for `next.www.documentcloud.org`.

Adds Plausible to AppLayout

---

src/lib/components/common/PlausibleTracker.svelte
src/lib/components/common/SignedIn.svelte
src/lib/components/forms/DocumentUpload.svelte
src/lib/components/forms/Projects.svelte
src/lib/components/layouts/DocumentBrowser.svelte
src/lib/components/layouts/DocumentLayout.svelte
src/lib/utils/permissions.ts
src/lib/utils/tests/permissions.test.ts
src/routes/(pages)/home/+page.svelte
src/routes/add-ons/[owner]/[repo]/+page.svelte
src/routes/add-ons/[owner]/[repo]/[event]/+page.svelte
src/routes/documents/+page.svelte
src/routes/documents/sidebar/Documents.svelte
src/test/components/UserContext.demo.svelte

- Adds utility functions for checking user permissions
- Adds a `getCurrentUser` helper that simplifies imports when getting `me` from context.
- Creates dedicated directory for storing our `*.demo.svelte` components.
This raises a design question: should we continue to use `<SignedIn>` and compose our permissions checks (expanding permission components to include `<CanUploadFiles>`), is an inline `{#if isSignedIn($me)}…{:else}…{/if}` a better approach, or are both valid?

Adds permissions utilities

---

src/lib/components/common/HighlightGroup.svelte

Based on the solution described in [this RFC](https://github.com/dummdidumm/rfcs/blob/ts-typedefs-within-svelte-components/text/ts-typing-props-slots-events.md#generics) and [this PR](https://github.com/sveltejs/language-tools/pull/2020), we should prefer defining generic types in a `generics` script tag attribute.

Uses generics script attribute

---

package-lock.json
package.json
src/common/Dropdown2.svelte
src/lib/components/accounts/tests/__snapshots__/UserMenu.test.ts.snap
src/lib/components/common/PageToolbar.svelte
src/lib/components/documents/toolbars/ReadingToolbar.svelte
src/lib/components/forms/Search.svelte
src/style/kit.css
svelte.config.js
vite.config.js
vitest-setup.js

This adds responsive logic for the viewer's search input, disclosing it inside a dropdown when on mobile. This prevents the viewer's top toolbar from overflowing the viewport at narrow screen widths.
In addition, this adds a preprocessor to modify the behavior of `bind:clientWidth`. [The default behavior adds `style="position: relative"`](https://github.com/sveltejs/svelte/issues/4776), which is undesirable for our toolbars, which rely on definite placement within the stacking context for correct menu behavior and sticky positioning. This preprocessor also uses a more performant method of binding to clientWidth by using `ResizeObserver` instead of `iframe` hackery. This might be fixed in Svelte 5.

Fix mobile viewer toolbars

---

src/lib/components/addons/AddOnMeta.svelte
src/lib/components/documents/DocumentListItem.svelte
src/lib/components/documents/tests/__snapshots__/DocumentListItem.test.ts.snap
src/lib/components/layouts/AddOnBrowser.svelte
src/lib/components/layouts/AddOnLayout.svelte
src/lib/components/layouts/ContentLayout.svelte
src/lib/components/layouts/DocumentBrowser.svelte
src/lib/components/layouts/DocumentLayout.svelte
src/lib/components/layouts/Sidebar.svelte
src/lib/components/layouts/SidebarLayout.svelte
src/lib/components/layouts/stories/AppLayout.stories.svelte

Fixes #702 
- Applies auto height to DocumentBrowser contents
- Consistent overflow scroll behavior between layout components
- Gives "background" styles to ContentLayout
- Styling cleanup and tweaks
- Passes through `disablePremium` prop to `AddOnDispatch`

Layout styling fixes

---

src/lib/api/documents.ts
src/lib/components/accounts/UserMenu.svelte
src/lib/components/documents/Note.svelte
src/lib/components/embeds/DocumentEmbed.svelte
src/lib/components/forms/ManageCollaborators.svelte
src/lib/components/forms/UserFeedback.svelte
src/lib/components/navigation/OrgMenu.svelte
src/lib/utils/search.ts

Closes #706
Uses our `getUserName` helper function to avoid directly accessing `user.name` and always return a string.

Handles undefined user.name

---

src/langs/json/en.json
src/lib/components/documents/Metadata.svelte
src/lib/components/documents/Text.svelte
src/lib/components/documents/Viewer.svelte
src/lib/components/documents/stories/Text.stories.svelte
src/lib/components/embeds/DocumentEmbed.svelte
src/lib/components/layouts/DocumentLayout.svelte
src/routes/(app)/documents/[id]-[slug]/+page.ts
src/routes/embed/documents/[id]-[slug]/+page.ts

Closes #713
This changes document loading to load text by default. This way, we don't need to `await` the data to render text-dependent information. Happy to reconsider this, but our current approach may load the text multiple times since we depend on it now in more than one place.

Display OCR engine in Document metadata

---

src/lib/components/layouts/AppLayout.svelte

Closes #694 by using `dvh` to adapt to changing viewport hight
This fixes the positioning of toolbars and elements, but does not go further in collapsing Mobile Safari's toolbar on scroll. That will require additional work, which I've captured as #729.

Fix Mobile Safari height

---

src/lib/components/layouts/Portal.svelte

Removes Portal from DOM when destroying

---

jsconfig.json
src/app.d.ts
src/routes/+layout.svelte
src/service-worker.ts
tsconfig.json

This uses the example service worker from the SvelteKit docs, plus update handling.
Check on staging that this doesn't interfere with writes.
Closes #548, #707

Use a service worker to cache requests

---

src/lib/components/forms/Edit.svelte
src/lib/components/forms/EditNote.svelte
src/lib/components/forms/EditProject.svelte
src/lib/components/forms/ManageCollaborators.svelte
src/lib/components/forms/Projects.svelte

Closes #743 
This should stop people from submitting forms with missing required fields.

Set required on required form inputs

---

.storybook/main.ts
src/style/kit.css

We needed to specify our static directories in the config. I also tried to ensure if Source Sans Pro is missing, we're falling back to a default `sans-serif` font instead of `serif`.

Fixes font loading in Storybooks

---

.github/workflows/test.yml

We've observed segmentation faults when running `vitest` in GitHub Actions. This may be because vitest runs multithreaded by default, and it uses too much memory in the task runner.
This adds the `--run` flag to our GitHub test workflow, which forces vitest to run sequentially. It may add a few seconds to overall test execution, but should be more stable.

Run `test` CI sequentially to avoid segmentation faults

---

.storybook/preview.ts
package-lock.json
package.json
src/lib/components/accounts/tests/__snapshots__/Mailkey.test.ts.snap
src/lib/components/common/Button.svelte
src/lib/components/layouts/Navigation.svelte
src/lib/components/layouts/Sidebar.svelte
src/lib/components/navigation/HelpMenu.svelte
src/lib/components/onboarding/GuidedTour.svelte
src/lib/components/onboarding/scripts.ts
src/lib/components/sidebar/SidebarGroup.svelte
src/routes/(app)/documents/+page.svelte
src/routes/(app)/documents/[id]-[slug]/+page.svelte

Closes #598
When users open the application for the first time, we can introduce them to the application with a guided tour. We can support unique tours for individual routes, giving us an opportunity to introduce key interfaces individually and as users encounter them. Tours are mounted to `+page.svelte` components.
This PR adds guided tours to two routes:
1. `/(app)/documents`, explaining the new browser UI layout
2. `/(app)/documents/[id]-[slug]`, explaining the new document viewer
We determine who is a "first-time" user with a value in `localStorage`. This could be enhanced by writing a value to the user in the database.
If a tour is available for a route, it can be triggered from the Help menu.
If you need to reset the feature's memory while testing, open up your devtools to the …

Guided tours for first-time users

---

netlify.toml
package-lock.json
package.json

Closes #527 
This adds a plugin to our Netlify deployments to automatically generates [Lighthouse scores and reports](https://developer.chrome.com/docs/lighthouse/overview) for each deployment. Lighthouse reports are included in the deployment comment added to each PR.
This gives us a good benchmark for our application's health and accessibility, with the option to "lock in" a score threshold to prevent regression. This threshold has not been set, but is left commented-out in the plugin configuration for future reference.

Adds Lighthouse plugin to Netlify config

---

package-lock.json
package.json
src/common/AccessIcon.svelte
src/common/Button.svelte
src/common/RevisionIcon.svelte
src/common/dialog/DocumentInformationDialog.svelte
src/common/dialog/MetaFieldDialog.svelte
src/lib/components/common/AddOns.svelte
src/lib/components/common/Tooltip.svelte
src/lib/components/common/stories/Tooltip.stories.svelte
src/lib/components/forms/DocumentUpload.svelte
src/lib/components/layouts/EmbedLayout.svelte
src/lib/components/processing/Documents.svelte
src/lib/components/viewer/toolbars/AnnotationToolbar.svelte
src/lib/components/viewer/toolbars/RedactionToolbar.svelte
src/pages/app/ActionBar.svelte
src/pages/app/DocumentThumbnail.svelte
src/pages/app/menus/ProjectMenuItem.svelte
src/style/kit.css

- Moves `Tooltip.svelte` from `src/common` to `src/lib/components/common`
- Adds stories for Tooltip
- Uses [Floating UI](https://floating-ui.com/) to compute tooltip position
I opted to replace the custom logic with Floating UI for a few reasons:
- We get more reliable functionality for shifting position and respecting window boundaries, with a well-tested and widely used library.
- We can use Floating UI in other components, like Dropdowns, without rewriting the logic.
- We can use Floating UI with `<canvas>` in the document viewer to enhance the interface (see #204)

Tooltip enhancements

---

src/lib/components/documents/DocumentListItem.svelte
src/lib/components/documents/tests/__snapshots__/DocumentListItem.test.ts.snap

Closes #669 
To test, upload [Learn How To Do Isochrones In A Minute.pdf](https://github.com/user-attachments/files/17101212/Learn.How.To.Do.Isochrones.In.A.Minute.pdf) to the preview deployment. It should have a thumbnail the same size as other documents.

Constrain tall document thumbnails

---

src/langs/json/en.json
src/lib/components/documents/Share.svelte
src/lib/components/documents/stories/Share.stories.svelte
src/lib/components/embeds/DocumentEmbed.svelte
src/lib/components/embeds/stories/DocumentEmbed.stories.svelte
src/lib/components/projects/ProjectHeader.svelte

Fixes #684
- When sharing a document, we notify the user if the access is `private` or `organization`. If the user can edit the document, then we give them an action to adjust the visibility settings.
- When embedding a document, we place a warning  in the embed if its access is not `public`. We give them a link to the document page to take action.

Privacy warning when sharing and embedding non-public documents

---

src/lib/components/documents/Projects.svelte
src/lib/components/forms/EditProject.svelte
src/lib/components/forms/Projects.svelte
src/lib/components/forms/stories/Projects.stories.svelte

Fixes #653
- Uses existing EditProject form in a modal, instead of inlining a custom form.
- Adds `on:success` event to EditProject form to allow adding created project to list of projects.

Separate project creation from project form

---

src/lib/components/forms/EditNote.svelte
src/lib/components/viewer/AnnotationLayer.svelte
src/lib/components/viewer/Note.svelte
src/lib/components/viewer/Notes.svelte
src/lib/components/viewer/ViewerContext.svelte
src/lib/components/viewer/stories/Viewer.stories.svelte

Fixes #689
- Save `newNote` to ViewerContext store for consistent `$newNote` value between multiple page AnnotationLayers
- Places a note above or below its highlight box based on how much space is available in the page
- Consistent styling for notes between reading/writing and inline/page
- Improve rendering for `currentNote` by deduplicating note objects

Improve note rendering

---

src/lib/components/viewer/LoadingToolbar.svelte
src/lib/components/viewer/ReadingToolbar.svelte
src/lib/components/viewer/Viewer.svelte
src/lib/components/viewer/ViewerContext.svelte
src/lib/components/viewer/stories/LoadingToolbar.stories.svelte

Fixes #547
I'm open to alternate placements, but this made sense to me: the viewer isn't fully interactive until the PDF loads.

Display PDF loading progress in header toolbar

---

src/lib/api/documents.ts

Fixes #791
We're already catching this in a bunch of places—there's just one function where we weren't.

Catch error when fetching private asset URL

---

src/lib/components/inputs/TextArea.svelte
src/lib/components/inputs/stories/Textarea.stories.svelte
src/lib/components/processing/stories/Process.stories.svelte

Fixes #672
This attempts to fix inconsistent snapshots in Chromatic snapshots.
This usually occurs when rendering an element with autoresizing textareas. 
Unfortunately, we won't know if it works until our usage resets on October 30!
- Uses experimental CSS rule `field-sizing: content` to automatically resize text areas in Chromium browsers
- Polyfills functionality with existing auto-resizing function, adjusted to wait until webfonts finish loading before running initial resize.
This prevents the textarea from resizing until the window is fully loaded, hopefully preveting inconsistent snapshots.
In addition, it excludes the "Process / In-Progress" story from snapshots, since it uses an animated, indeterminate progress indicator. This serves as an example for how to remove other animated …

Stabilize Chromatic snapshots

---

.github/workflows/chromatic.yml
src/lib/api/documents.ts
src/lib/api/tests/documents.test.ts
src/lib/components/documents/Access.svelte
src/lib/components/documents/DocumentListItem.svelte
src/lib/components/documents/stories/DocumentListItem.stories.svelte
src/lib/components/documents/stories/ResultsList.stories.svelte
src/lib/components/documents/tests/__snapshots__/DocumentListItem.test.ts.snap

Closes #790
We already have the capability to display projects on document search results, but we weren't expanding them in the API request.

Expand projects in document search results

---

src/lib/components/viewer/PageActions.svelte

Fix #800
When the PageActions were refactored, we didn't update the modal and form `on:close` handlers. This fixes that.

Fix close handlers on PageAction modals

---

src/lib/components/viewer/PDF.svelte
src/lib/components/viewer/ViewerContext.svelte
src/lib/components/viewer/stories/PDF.stories.svelte

Fixes #758
Doesn't address the root causes of `InvalidPDFException`, but will catch and display the error instead of crashing the viewer.

Handles errors when rendering PDF in viewer

---

src/lib/components/layouts/DocumentLayout.svelte
src/lib/components/viewer/PDF.svelte
src/lib/components/viewer/ViewerContext.svelte
src/routes/+layout.svelte

Fixes a regression where documents still processing wouldn't load. Now we can see them again.

Calculate sizes when the PDF loads, not in onMount

---

src/lib/components/documents/Access.svelte
src/lib/components/documents/Header.svelte
src/lib/components/layouts/DocumentLayout.svelte

This was a small thing that was bugging me. Now document header is consistent with project header. Access, a non-interactive element, is out of right sidebar (interactive elements). I've also scaled down the document title's font size.

Move access into document header

---

src/lib/components/documents/ResultsList.svelte
src/lib/components/documents/tests/ResultsList.test.ts
src/lib/components/forms/BulkActions.svelte
src/lib/components/inputs/Selection.svelte
src/lib/components/layouts/AddOnLayout.svelte
src/lib/components/layouts/DocumentBrowser.svelte
src/routes/(app)/documents/sidebar/Actions.svelte

Closes #798 
This ensures we know what's selected based on IDs even when the document objects can't be directly compared.

Derive selected documents from selected IDs

---

src/lib/components/common/Paginator.svelte
src/lib/components/forms/Reprocess.svelte
src/lib/components/inputs/Language.svelte
src/lib/components/layouts/ContentLayout.svelte
src/lib/components/layouts/DocumentLayout.svelte
src/lib/components/layouts/stories/EmbedLayout.stories.svelte
src/lib/components/viewer/Notes.svelte
src/lib/components/viewer/PDF.svelte
src/lib/components/viewer/PaginationToolbar.svelte
src/lib/components/viewer/Text.svelte
src/lib/components/viewer/Viewer.svelte
src/lib/components/viewer/ViewerContext.svelte
src/lib/components/viewer/stories/Text.stories.svelte
src/lib/load/document.ts
src/routes/(app)/documents/[id]-[slug]/+page.svelte
src/routes/(app)/documents/[id]-[slug]/+page.ts
src/routes/embed/documents/[id]-[slug]/+page.svelte
src/routes/embed/documents/[id]-[slug]/+page.ts
svelte.config.js

Fixes #837 
Test URL: https://deploy-preview-839.muckcloud.com/documents/20006876-2017-epa-staff-calendars-part2-s/
The issue seems to be that server-side rendering every page in a giant document produces a huge HTML page that's too big for our Lambda workers to push it through. 
This PR fixes it, but we should do another pass and see if we can slim down our pages further.

Delay loading to shrink page size

---

src/lib/components/documents/Header.svelte
src/lib/components/documents/stories/Header.stories.svelte

Fixes #835
Adds Storybook to recreate issue

Handle long, unbroken document titles on viewer page

---

src/lib/components/documents/NoteHighlights.svelte
src/lib/components/documents/PageHighlights.svelte

Fixes #848
Default `open = true` for page and note highlight groups

Show search result snippets by default

---

src/config/config.js
src/langs/json/en.json
src/lib/components/accounts/Unverified.svelte
src/lib/components/accounts/stories/Unverified.stories.svelte
src/lib/components/common/Tip.svelte
src/lib/components/common/stories/Tip.stories.svelte
src/lib/components/documents/ResultsList.svelte
src/lib/components/documents/stories/ResultsList.stories.svelte
src/lib/components/forms/DocumentUpload.svelte
src/lib/components/forms/stories/DocumentUpload.stories.svelte
src/lib/components/forms/tests/DocumentUpload.test.ts
src/lib/components/layouts/DocumentBrowser.svelte

Feedback welcome on the text here and the icon. Closes #841.
Text:
- `verify`: "Before you can upload documents, you need to be verify your account. You can do this by joining a verified news organization or by requesting verification for yourself.",
- `allowed_actions`: "Until you're verified, you can search through the public repository, organize documents you're interested in into projects, leave private notes, and collaborate on editing and annotating documents other users invite you to."

Show message and links to unverified users

---

src/lib/components/forms/Search.svelte
src/lib/components/viewer/PDFPage.svelte
src/lib/components/viewer/ReadingToolbar.svelte
src/lib/components/viewer/Text.svelte
src/lib/components/viewer/ViewerContext.svelte
src/lib/components/viewer/stories/PDFPage.stories.svelte
src/lib/utils/search.ts
src/routes/(app)/documents/[id]-[slug]/+page.svelte
src/routes/(app)/projects/+page.svelte
src/routes/embed/documents/[id]-[slug]/+page.ts

Closes #846 and consolidates routing logic around search.
For PDF pages, we're now getting the search query directly from the URL, instead of props, and reacting to URL changes.

Fix viewer search and consolidate search routing, too

---

src/hooks.server.ts
src/lib/components/documents/Access.svelte
src/lib/components/documents/BulkActions.svelte
src/lib/i18n/index.js
src/lib/utils/language.ts
src/lib/utils/tests/language.test.ts
src/routes/+layout.ts

Trying to solve #818 
My browser sets the `accept-language` header and `window.navigator.language` to `en-US`, but we weren't registering that as a locale, only `en`. So this adds that registration and also standardizes our own setting to `en`.

Standardize on 'en', not 'en-US' as a language code, but register both

---

src/langs/json/en.json
src/lib/components/forms/Search.svelte
src/lib/components/forms/stories/Search.stories.svelte
src/lib/components/layouts/DocumentBrowser.svelte

Add a slot to show search tips

---

src/lib/components/viewer/AnnotationLayer.svelte
src/lib/components/viewer/Page.svelte
src/lib/components/viewer/ReadingToolbar.svelte
src/lib/utils/tests/viewer.test.ts
src/lib/utils/viewer.ts

Staying seamless while maintaining URL state.

Pass query through viewer links between modes

---

CHANGELOG.md

Edits welcome. The goal here is to get us started.

Draft a changelog

---

src/langs/json/en.json
src/lib/components/addons/History.svelte
src/lib/components/addons/Scheduled.svelte
src/lib/components/documents/ResultsList.svelte
src/lib/components/documents/stories/ResultsList.stories.svelte
src/test/handlers/documents.ts

Closes #829 
This aligns our infinite scroll handling with other places we hit the API and lets us show an error message when something fails.

Use getApiResponse on infinite scrolls, too

---

src/lib/api/types.d.ts
src/lib/components/layouts/Project.svelte
src/lib/utils/search.ts

We were already doing this with users and orgs. Now when we link to a project query, we use the slug there, too. For example, `+project:200002` is now `+project:test-2-200002`.

Add project slugs to search queries for readability

---

src/lib/components/projects/ProjectPin.svelte

Enable pinning based on logged-in status, not project.edit_access

---

src/lib/components/accounts/tests/__snapshots__/UserMenu.test.ts.snap
src/lib/components/common/Menu.svelte
src/lib/components/navigation/OrgMenu.svelte
src/lib/components/navigation/stories/OrgMenu.stories.svelte

Fixes #872
When a menu has a max-height set, it's overflow will be scrollable.

Adds max-height option to Menu

---

package-lock.json
package.json
src/app.d.ts
src/config/config.js
src/hooks.server.ts
src/langs/json/en.json
src/lib/components/common/Toast.svelte
src/lib/components/forms/DocumentUpload.svelte
src/lib/components/forms/EditData.svelte
src/lib/components/forms/UserFeedback.svelte
src/lib/components/forms/stories/UserFeedback.stories.svelte
src/lib/components/layouts/Toaster.svelte
src/lib/components/layouts/stories/Toaster.stories.svelte
src/lib/components/sidebar/DocumentActions.svelte
src/routes/(app)/+page.server.ts
src/routes/(app)/add-ons/[owner]/[repo]/+page.server.ts
src/routes/(app)/add-ons/[owner]/[repo]/[event]/+page.server.ts
src/routes/(app)/documents/+page.server.ts
src/routes/(app)/documents/[id]-[slug]/+page.server.ts
src/routes/(app)/projects/+page.server.ts
src/routes/(app)/projects/[id]-[slug]/+page.server.ts
src/routes/+layout.server.ts
src/routes/+layout.svelte

Fixes #838
- Fixes Toaster to top-center
- Adds [sveltekit-flash-message](https://github.com/ciscoheat/sveltekit-flash-message?tab=readme-ov-file) library to set and fetch toast data in cookies, allowing for server actions to send toasts to the frontend.
- Sends toasts from our server actions for errors and successes.
- Sends client-side toasts from the DocumentUpload form.
- Server-side toasts are hardcoded English strings until we address #899

More comprehensive Toast notifications

---

src/config/config.js
src/routes/(app)/+layout.ts
src/routes/(app)/+page.server.ts
src/routes/(app)/add-ons/+layout.ts
src/routes/(app)/documents/+layout.ts
src/routes/(app)/projects/[id]-[slug]/+page.ts
src/routes/(app)/upload/+page.ts
src/routes/(pages)/[...path]/+page.ts
src/routes/(pages)/home/+page.ts
src/routes/embed/documents/[id]-[slug]/+page.ts
src/routes/embed/documents/[id]/annotations/[note_id]/+page.ts
src/routes/embed/documents/[id]/pages/[page]/+page.ts
src/routes/embed/projects/[project_id]-[slug]/+page.ts

Closes #898 and a little more.
- **Set basic cache headers on embeds**
- **Set cache headers on pages**
- **projects, add-ons, redirect upload if not-logged in**
- **documents**
There are three new config values to set default cache timeouts, so we can adjust routes with a little granularity. Everything is set for 10 minutes for now.

Set cache headers for anonymous users

---

src/lib/components/layouts/DocumentLayout.svelte
src/lib/components/sidebar/ViewerActions.svelte
src/lib/components/viewer/ReadingToolbar.svelte

Note that the legacy link will only work on production. Other environments will 404 (because staging has its own database).

Add link and messaging about search and legacy mode

---

src/config/config.js
src/lib/components/common/Toast.svelte
src/lib/components/layouts/Toaster.svelte

Tweaks to toast appearance:
- Stronger shadow
- 500ms longer until they disappear

Toast tweaks

---

src/lib/components/layouts/DocumentBrowser.svelte

Hide search tip on mobile

---

src/lib/components/common/Paginator.svelte
src/lib/components/processing/Process.svelte
src/lib/components/viewer/LoadingToolbar.svelte
src/routes/(app)/projects/+page.svelte
src/routes/(app)/projects/+page.ts

This fixes #920 by improving how we call `next` and `previous` in `Pagination.svelte`

"Your Projects" list not showing all projects

---

src/lib/api/documents.ts
src/lib/api/tests/documents.test.ts

Guard against fetch failures in `textPositions`

---

src/routes/(app)/+page.ts
src/routes/(app)/app/+page.ts

Closes #945 
Clones the URL, change the path but preserves other properties, including querystring.

Preserve querystrings on redirects

---

src/lib/api/accounts.ts
src/lib/api/addons.ts
src/lib/api/collaborators.ts
src/lib/api/documents.ts
src/lib/api/flatpages.ts
src/lib/api/notes.ts
src/lib/api/projects.ts
src/lib/api/sections.ts
src/lib/api/tests/addons.test.ts
src/lib/components/addons/AddOnPin.svelte
src/lib/components/addons/History.svelte
src/lib/components/addons/Scheduled.svelte
src/lib/components/documents/ResultsList.svelte
src/lib/components/processing/AddOns.svelte
src/lib/components/projects/ProjectPin.svelte
src/lib/components/viewer/PDF.svelte
src/lib/components/viewer/ViewerContext.svelte
src/lib/utils/api.ts
src/lib/utils/scroll.ts
src/lib/utils/search.ts

Tell Sentry these aren't as high a priority as other errors.

Use console.warn instead of console.error when we catch a failed fetch

---

CHANGELOG.md
package.json

Capturing changes and bug fixes post-launch. Also did an overdue major version bump in `package.json`.

changelog 2024 12 06

---

src/lib/components/viewer/Grid.svelte

Limit the bandwidth we send in `grid` mode, like we do with `document` and `text` modes.

Only render page grid in the browser

---

src/langs/json/de.json
src/langs/json/en.json
src/langs/json/es.json
src/langs/json/fr.json
src/langs/json/it.json
src/langs/json/ru.json
src/langs/json/uk.json
src/lib/components/accounts/tests/__snapshots__/UserMenu.test.ts.snap
src/lib/components/addons/tests/__snapshots__/AddOnsNavigation.test.ts.snap
src/lib/components/common/KV.svelte
src/lib/components/common/Menu.svelte
src/lib/components/documents/DocumentListItem.svelte
src/lib/components/documents/ResultsList.svelte
src/lib/components/documents/Thumbnail.svelte
src/lib/components/documents/VisibleFields.svelte
src/lib/components/documents/stories/DocumentListItem.stories.svelte
src/lib/components/documents/stories/Thumbnail.stories.svelte
src/lib/components/documents/stories/VisibleFields.stories.svelte
src/lib/components/documents/tests/__snapshots__/DocumentListItem.test.ts.snap
src/lib/components/layouts/DocumentBrowser.svelte
src/lib/components/layouts/DocumentListToolbar.svelte
src/lib/components/layouts/stories/DocumentBrowser.stories.svelte
src/lib/components/sidebar/SidebarItem.svelte
src/lib/components/viewer/AnnotationLayer.svelte
src/lib/components/viewer/NoteTab.svelte
src/test/fixtures/documents.ts

So many people have their own opinions for what belongs in a document search result. Instead of a one-size fits all solution, this allows for users to override a set of opinionated defaults.
**[`VisibleFields` storybook](https://6567908438a7a23eba571d04-wtawxoxdur.chromatic.com/?path=/story/components-documents-visible-fields--balanced)**
Resolves #881, resolves #834
- Updates styling for document list items
- Splits out anchor links within document list item
- Updates apperance and generic logic of KV component, so it can adapt to being a link
- Uses `StorageManager` to remember a user's `VisibleFields` preferences.
- Add a dropdown menu to DocumentBrowser's top toolbar for users to toggle fields.

Allow users to customize DocumentListItem

---

src/lib/api/feedback.ts
src/lib/components/forms/UserFeedback.svelte
src/routes/(app)/+page.server.ts

We get a lot of anonymous feedback about loading issues. By adding the page URL to the feedback payload, we can better target diagnoses.

Capture page URL for feedback

---

src/lib/components/documents/Header.svelte
src/lib/components/documents/Metadata.svelte
src/lib/components/documents/stories/Metadata.stories.svelte
src/lib/components/layouts/DocumentLayout.svelte
src/lib/components/layouts/SidebarLayout.svelte
src/lib/components/sidebar/ViewerActions.svelte

Update documents for logged out users

---

src/lib/components/viewer/AnnotationLayer.svelte
src/lib/components/viewer/RedactionLayer.svelte

Fixes #969
As a bonus, slight improvement to annotation box drawing logic, too!
Doesn't consolidate the logic, since it depends on global variables to work correctly. Could be revisited in the future.

Fix redaction box drawing logic

---

src/langs/json/en.json
src/lib/components/forms/ConfirmRedaction.svelte
src/lib/components/viewer/RedactionLayer.svelte

Clean up redaction layer between routes

---

src/lib/components/viewer/ViewerContext.svelte
src/lib/components/viewer/stories/Viewer.stories.svelte
src/test/handlers/viewer.ts

Fixes #836
When we're fetching a private asset and we get a 403 response, try refetching the private asset URL and trying again (up to a maximum of 5 tries).

Attempted fix for private PDF 403 error

---

src/routes/embed/+layout.ts

We're burning through our functions quota on Netlify serving embeds, which are almost entirely client-side rendered anyway.

Embeds don't need SSR

---

src/lib/components/common/Tab.svelte
src/lib/components/viewer/ReadingToolbar.svelte
src/lib/components/viewer/Search.svelte
src/lib/utils/navigation.ts
src/lib/utils/tests/navigation.test.ts

Closes #933 
Example URL: https://deploy-preview-985.muckcloud.com/documents/20006908-lawsuit-document-dkt-1-68-ex-j/?q=apple&mode=search&embed=1&title=0
Clicking links in search or the `mode` tabs should keep you in the embed viewer and preserve params like `title=0`.

Preserve search params when navigating within the viewer

---

src/lib/components/viewer/PaginationToolbar.svelte
src/lib/components/viewer/Search.svelte

Was getting a warning about eagerly calling fetch.

Check that we're in the browser before calling searchWithin

---

netlify.toml
src/config/config.js
src/routes/(app)/documents/[id]-[slug]/+page.svelte
src/routes/embed/+layout.ts

Also fix the off-by-one on social cards.

Re-enable embed SSR

---

src/config/config.js
src/lib/components/layouts/EmbedLayout.svelte

Setting cache headers on embeds and flat pages to 24 hours.

Dial up caching and allow overrides through env

---

jsconfig.json
netlify.toml
src/config/embed.js
src/embed/enhance.js
src/embed/noteLoader.js
src/embed/projectLoader.js

The `$env/static/public` import was breaking our embed scripts, which made me realize we were importing a bunch of unneeded config in those anyway. This fixes both problems.

Give embeds a minimal config to exclude unused imports

---

src/langs/json/en.json
src/lib/components/forms/DocumentUpload.svelte

Fixes #983
When the upload form isn't empty or is loading, show a confirmation dialog before completing a navigation away.

Show confirmation when navigating away from in-progress upload form

---

src/routes/(pages)/[...path]/+page.ts
src/routes/(pages)/home/+page.ts
src/routes/+layout.ts
src/routes/embed/+layout.ts

See if this solves #1006 
My theory is that requests to missing assets are being caught by the flat page route, which tries to normalize to a trailing slash. This will still trigger one function call with a 404, but not two -- a redirect and then a 404.
We may be able to further optimize this by using a more specific flat page route.

Ignore trailing slashes for flat pages

---

src/app.d.ts
src/hooks.server.ts
src/lib/utils/logging.ts

Closes #1012 
Logs are here: https://app.netlify.com/sites/documentcloud-frontend-next/logs/functions/sveltekit-render?scope=deploypreview:1015
This logs:
- date
- method
- url
- status
- route ID, like `(app)/documents/[id]-[slug]`
- etag
- cache control header

Let's log things

---

src/lib/components/onboarding/GuidedTour.svelte
src/routes/(app)/documents/[id]-[slug]/+page.server.ts
src/routes/(app)/documents/[id]-[slug]/+page.svelte
src/routes/(app)/documents/[id]-[slug]/+page.ts
src/routes/embed/+layout.ts

- **Detect iframe in doc viewer and goto embed**
- **Check for Sec-Fetch-Dest header and redirect if we see it**
- **Ignore trailing slashes on embeds**
When I tested locally, iframes aren't sending the `Sec-Fetch-Dest` header in Chrome, but setting it with `curl` triggers the correct redirect. Firefox is setting that header and it works as expected, so that's something.
Closes #1008

Detect iframes

---

src/routes/(pages)/about/+page.svelte
src/routes/(pages)/about/+page.ts
src/routes/(pages)/help/[...path]/+page.svelte
src/routes/(pages)/help/[...path]/+page.ts

Lots of missing assets are being served as flatpage 404s instead of letting Netlify serve a plain text 404. This narrows the route matching to avoid that.
The only flat pages outside of `/help/` are `/home/` and `/about/`, so there's a dedicated route for each of those now.

Don't just catch everything as a flat page

---

src/lib/api/documents.ts
src/lib/api/tests/documents.test.ts
src/lib/load/document.ts
src/routes/(app)/documents/[id]-[slug]/+page.ts

Log a URL that throws an error

---

src/routes/(app)/documents/[id]-[slug]/+page.svelte

Since `embed.documentcloud.org` is technically an external domain.

Set window.location instead of using goto

---

src/lib/utils/embed.ts
src/lib/utils/tests/embed.test.ts

SvelteKit is serving 404 pages to missing static files and other things that it shouldn't. This should save us some bandwidth, at least.
Example: https://embed.documentcloud.org/_app/immutable/chunks/navigation.CziXxwWJ.js (may need a hard refresh if your browser cached it).

Embeds only start with /projects or /documents

---

src/langs/json/en.json
src/lib/components/layouts/Error.svelte
src/lib/components/layouts/stories/Error.stories.svelte
src/routes/(app)/+error.svelte
src/routes/(app)/add-ons/+error.svelte
src/routes/(app)/add-ons/[owner]/[repo]/+error.svelte
src/routes/(app)/documents/+error.svelte
src/routes/(app)/documents/[id]-[slug]/+error.svelte
src/routes/(app)/projects/+error.svelte
src/routes/(app)/projects/[id]-[slug]/+error.svelte
src/routes/(app)/upload/+error.svelte
src/routes/(pages)/+error.svelte
src/routes/+error.svelte

When a user hits a 404 page, they may not know whether they're signed in or not. This can be problematic on private documents. Here, we check the status and the session, prompting the user to sign in if they're not already authenticated.

Adds a helpful message on 404 pages if the user is signed out

---

.gitignore
README.md
package.json
src/config/config.js
src/config/remote.js
vite.config.js

Closes #677
Adds a new `npm run dev:remote` command that runs the Vite dev server against our staging APIs for DocumentCloud and Squarelet. This removes the dependency on a local stack to do frontend development.
The steps required for setup are detailed in the README. This approach leverages our support for Netlify Deploy Previews by aliasing localhost as another `*.muckcloud.com` subdomain.

Run local dev server against staging API

---

src/lib/components/common/PlausibleTracker.svelte
src/routes/(pages)/help/[...path]/+page.svelte
src/routes/(pages)/home/+page.svelte

Closes #1011 
For the home page, I just added the `<PlausibleTracker />` component at the bottom, since we just need it on the page and it doesn't need to wrap anything.

Add plausible to flat pages

---

src/lib/api/documents.ts
src/lib/api/tests/documents.test.ts
src/lib/api/types.d.ts
src/lib/utils/pageSize.ts

Closes #1036 
This adds a `t=<timestamp>` to text and text position asset URLs on public documents. (Private documents aren't cached the same way.)

Add cache busting to public asset URLs

---

src/config/config.js
src/langs/json/en.json
src/lib/api/documents.ts
src/lib/api/tests/documents.test.ts
src/lib/components/common/Tip.svelte
src/lib/components/common/stories/Tip.stories.svelte
src/lib/components/forms/EditMany.svelte
src/lib/components/forms/stories/Edit.stories.svelte
src/routes/(app)/documents/+page.server.ts

This is a short term fix, with hooks to adjust as we go. I've limited bulk editing to 25 documents at a time, disabling the form if you've selected more. We can do two things to increase that in two ways:
- increase the backend limit
- batch requests
Both of those have tradeoffs and we should talk about them, but this will keep people from hitting unexpected errors.

Limit bulk editing to 25 documents at a time, show errors

---

src/lib/api/addons.ts
src/lib/api/tests/addons.test.ts
src/lib/components/layouts/AddOnLayout.svelte
svelte.config.js

Maybe handles #929 
Checkbox inputs send a value of `"on"`, so we need to convert it to a boolean by hand.

Handle boolean fields in addon forms

---

src/lib/components/common/MenuItem.svelte
src/lib/components/viewer/ReadingToolbar.svelte
src/lib/utils/navigation.ts
src/lib/utils/tests/navigation.test.ts

Fixes #1056 
The `MenuItem` component now takes a `preserveQS` flag, which enables the `qs` action. That action now has an `enabled` argument, which defaults to true. On `MenuItem`, `preserveQS` defaults to false.

Preserve querystring in menu items (sometimes)

---

src/lib/components/viewer/PaginationToolbar.svelte

This applies to embeds and the regular viewer. If you don't have edit access and there are no sections, there's no point showing you the empty menu.
Closes #1058

Hide empty sections menu for non-editors

---

src/hooks.client.ts
src/hooks.server.ts

This should let us filter errors by `hostname` or `server` (in client and server, respectively), and hopefully let us see where some weird non-crashing errors are happening.

Set sentry environment for better filtering

---

src/lib/components/common/Highlight.svelte

Closes #1071 
Just removes the `ellipses` class on the `p` tag.

Don't truncate search highlights

---

src/lib/components/viewer/AnnotationLayer.svelte
src/lib/components/viewer/Note.svelte

- **Remove duplicate modal for page-level notes**
- **Page-level notes don't open and get better styles**
Closes #1065
In the course of this, I realized that page-level notes weren't obvious as their own thing, so I added a border and background to make them more obvious and separate them from the page itself.

Fixes for page-level notes

---

src/lib/api/documents.ts
src/lib/api/tests/documents.test.ts
src/lib/components/addons/tests/__snapshots__/AddOnListItem.test.ts.snap
src/lib/components/forms/EditMany.svelte
src/routes/(app)/documents/+page.server.ts

Addressing https://github.com/MuckRock/documentcloud/issues/284
The `expand` flag was creating a slow request on the backend, even for one document, so this removes it for now.

Don't expand bulk update calls

---

src/lib/components/layouts/EmbedLayout.svelte
src/lib/utils/tests/embed.test.ts
src/routes/embed/documents/[id]-[slug]/+page.ts

Attempted fix for #1112
The default value for `fullscreen` is `null`, so when we checked `settings.fullscreen`, it would return false by default when we want true. So now we check for an explicit opt-out, `settings.fullscreen !== 0`.
This fix is reflected by changes to our Storybook diffs.

Only hide fullscreen embed action when explicitly disabled

---

src/lib/components/common/RelativeTime.svelte
src/lib/components/documents/Revisions.svelte
src/routes/(app)/documents/[id]/+page.ts
src/routes/embed/documents/[id]/+page.ts

This handles a URL structure we used to support -- `/documents/<id>/` -- which will now redirect to the canonical or embed route, as appropriate.
Closes #1111 
Test URLs:
- App: https://deploy-preview-1114.muckcloud.com/documents/20006908
- Embed: https://deploy-preview-1114.muckcloud.com/documents/20006908?embed=1&title=0
Those should redirect to working URLs with slugs.

Add redirects for bare ID routes

---

src/routes/(app)/+page.ts
src/routes/(app)/app/+page.ts
src/routes/(pages)/home/+page.ts
static/_redirects

Tweaking some redirects to reduce unnecessary requests:
- `/app` ignores trailing slashes, so we don't do `/app` -> `/app/` -> `/documents/`
- `/home` ignores trailing slashes because we don't care
- `/api/oembed.json` in `_redirects` because CF doesn't always catch that

catch more redirects

---

src/lib/utils/logging.ts

Closes #1117 
This doesn't change anything about error logging, so we may have to filter out errors to put requests in a database.

Log requests as a line of JSON for easier parsing

---

src/lib/utils/embed.ts
src/routes/embed/documents/[id]/annotations/[note_id]/+page.svelte
src/routes/embed/documents/[id]/pages/[page]/+page.svelte

Note and page embeds weren't resizing because sometimes the `postMessage` wasn't happening at the right time. This restores old behavior where it sends on each window resize, throttled to each half second.
See it live here: https://muckrock.github.io/documentcloud-embed-examples/note.html
Closes #1158

Resize on an interval again

---

src/lib/components/embeds/DocumentEmbed.svelte
src/lib/components/layouts/EmbedLayout.svelte
src/routes/embed/documents/[id]/annotations/[note_id]/+page.svelte
src/routes/embed/stories/note-embed.stories.svelte

- Document embeds don't lose their toolbars when scrolling
- Note embeds overflow scroll when the container is too small and center when the  container is too big. This lets us safely set a default height of 400-500px for note embeds.

Fixes for embeds

---

src/routes/(app)/add-ons/+layout.ts
src/routes/(app)/documents/+page.ts
src/routes/(app)/documents/[id]-[slug]/+page.ts
src/routes/(app)/projects/[id]-[slug]/+page.ts
src/routes/(pages)/about/+page.ts
src/routes/(pages)/help/[...path]/+page.ts
src/routes/(pages)/home/+page.ts
src/routes/embed/documents/[id]-[slug]/+page.ts
src/routes/embed/documents/[id]/annotations/[note_id]/+page.ts
src/routes/embed/documents/[id]/pages/[page]/+page.ts
src/routes/embed/projects/[project_id]-[slug]/+page.ts

This changes our cache header from `cache-control` to `Cloudflare-CDN-Cache-Control`, which means only Cloudflare actually caches it. Both netlify and browsers will ignore this header.
Part of #1146

Use cloudflare-specific cache header
